const db = [
  {"un": "1001", "nameTW": "乙炔 (電土氣 / Acetylene)", "nameEN": "Acetylene", "cas": "74-86-2", "class": "2.1", "nfpa": {"h": "1", "f": "4", "r": "3", "s": ""},
  {"un": "1005", "nameTW": "氨 (無水 / 阿摩尼亞 / 氨氣)", "nameEN": "Ammonia", "cas": "7664-41-7", "class": "2.3", "nfpa": {"h": "3", "f": "1", "r": "0", "s": ""},
  {"un": "1011", "nameTW": "丁烷 (桶裝瓦斯)", "nameEN": "Butane", "cas": "106-97-8", "class": "2.1", "nfpa": {"h": "1", "f": "4", "r": "0", "s": ""},
  {"un": "1013", "nameTW": "二氧化碳 (乾冰 / CO2)", "nameEN": "Carbon dioxide", "cas": "124-38-9", "class": "2.2", "nfpa": {"h": "1", "f": "0", "r": "0", "s": "SA"},
  {"un": "1016", "nameTW": "一氧化碳 (CO)", "nameEN": "Carbon monoxide", "cas": "630-08-0", "class": "2.3", "nfpa": {"h": "3", "f": "4", "r": "0", "s": ""},
  {"un": "1017", "nameTW": "氯氣 (氯 / Cl2)", "nameEN": "Chlorine", "cas": "7782-50-5", "class": "2.3", "nfpa": {"h": "4", "f": "0", "r": "0", "s": "OX"},
  {"un": "1049", "nameTW": "氫氣 (氫 / 氫氣)", "nameEN": "Hydrogen", "cas": "1333-74-0", "class": "2.1", "nfpa": {"h": "0", "f": "4", "r": "0", "s": ""},
  {"un": "1050", "nameTW": "氯化氫 (無水 / 鹽酸氣 / HCl)", "nameEN": "Hydrogen chloride", "cas": "7647-01-0", "class": "2.3", "nfpa": {"h": "3", "f": "0", "r": "1", "s": ""},
  {"un": "1053", "nameTW": "硫化氫 (H2S / 沼氣臭)", "nameEN": "Hydrogen sulfide", "cas": "7783-06-4", "class": "2.3", "nfpa": {"h": "4", "f": "4", "r": "0", "s": ""},
  {"un": "1066", "nameTW": "氮氣 (氮 / N2)", "nameEN": "Nitrogen", "cas": "7727-37-9", "class": "2.2", "nfpa": {"h": "0", "f": "0", "r": "0", "s": "SA"},
  {"un": "1072", "nameTW": "氧氣 (氧 / O2)", "nameEN": "Oxygen", "cas": "7782-44-7", "class": "2.2", "nfpa": {"h": "0", "f": "0", "r": "0", "s": "OX"},
  {"un": "1073", "nameTW": "液氧 (LOX / 液態氧)", "nameEN": "Oxygen, liquid", "cas": "7782-44-7", "class": "2.2", "nfpa": {"h": "3", "f": "0", "r": "0", "s": "OX"},
  {"un": "1075", "nameTW": "液化石油氣 (LPG / 桶裝瓦斯)", "nameEN": "L.P.G.", "cas": "68476-85-7", "class": "2.1", "nfpa": {"h": "1", "f": "4", "r": "0", "s": ""},
  {"un": "1971", "nameTW": "天然氣 (甲烷 / LNG / 管線瓦斯)", "nameEN": "Methane, compressed", "cas": "74-82-8", "class": "2.1", "nfpa": {"h": "1", "f": "4", "r": "0", "s": ""},
  {"un": "1977", "nameTW": "液氮 (LN2 / 液態氮)", "nameEN": "Nitrogen, liquid", "cas": "7727-37-9", "class": "2.2", "nfpa": {"h": "3", "f": "0", "r": "0", "s": "CRYO"},
  {"un": "1038", "nameTW": "液烯 (液化乙烯)", "nameEN": "Ethylene, liquid", "cas": "74-85-1", "class": "2.1", "nfpa": {"h": "3", "f": "4", "r": "2", "s": "CRYO"},
  {"un": "1076", "nameTW": "光氣 (COCl2)", "nameEN": "Phosgene", "cas": "75-44-5", "class": "2.3", "nfpa": {"h": "4", "f": "0", "r": "1", "s": ""},
  {"un": "1086", "nameTW": "氯乙烯 (VCM)", "nameEN": "Vinyl chloride", "cas": "75-01-4", "class": "2.1", "nfpa": {"h": "2", "f": "4", "r": "2", "s": ""},
  {"un": "1033", "nameTW": "二甲醚 (DME)", "nameEN": "Dimethyl ether", "cas": "115-10-6", "class": "2.1", "nfpa": {"h": "1", "f": "4", "r": "1", "s": ""},
  {"un": "1062", "nameTW": "溴化甲烷 (溴甲烷)", "nameEN": "Methyl bromide", "cas": "74-83-9", "class": "2.3", "nfpa": {"h": "3", "f": "1", "r": "0", "s": ""},
  {"un": "2203", "nameTW": "矽烷 (SiH4 / 矽甲烷)", "nameEN": "Silane", "cas": "7803-62-5", "class": "2.1", "nfpa": {"h": "1", "f": "4", "r": "2", "s": ""},
  {"un": "2199", "nameTW": "磷化氫 (PH3 / 磷化氫)", "nameEN": "Phosphine", "cas": "7803-51-2", "class": "2.3", "nfpa": {"h": "4", "f": "4", "r": "2", "s": ""},
  {"un": "1749", "nameTW": "三氟化氯 (ClF3 / 燃燒玻璃)", "nameEN": "Chlorine trifluoride", "cas": "7790-91-2", "class": "2.3", "nfpa": {"h": "4", "f": "0", "r": "3", "s": "W,OX"},
  {"un": "1911", "nameTW": "乙硼烷 (B2H6 / 硼烷)", "nameEN": "Diborane", "cas": "19237-62-4", "class": "2.3", "nfpa": {"h": "4", "f": "4", "r": "3", "s": "<s>W</s>"},
  {"un": "2188", "nameTW": "砷化氫 (AsH3 / 胂)", "nameEN": "Arsine", "cas": "7784-42-1", "class": "2.3", "nfpa": {"h": "4", "f": "4", "r": "2", "s": ""},
  {"un": "2451", "nameTW": "三氟化氮 (NF3)", "nameEN": "Nitrogen trifluoride", "cas": "7783-54-2", "class": "2.2", "nfpa": {"h": "1", "f": "0", "r": "0", "s": "OX"},
  {"un": "1080", "nameTW": "六氟化硫 (SF6 / 絕緣氣體)", "nameEN": "Sulfur hexafluoride", "cas": "2551-62-4", "class": "2.2", "nfpa": {"h": "1", "f": "0", "r": "0", "s": ""},
  {"un": "2192", "nameTW": "鍺烷 (GeH4)", "nameEN": "Germane", "cas": "7782-65-2", "class": "2.3", "nfpa": {"h": "4", "f": "4", "r": "1", "s": ""},
  {"un": "2196", "nameTW": "六氟化鎢 (WF6)", "nameEN": "Tungsten hexafluoride", "cas": "7783-82-6", "class": "2.3", "nfpa": {"h": "4", "f": "0", "r": "1", "s": ""},
  {"un": "1008", "nameTW": "三氟化硼 (BF3)", "nameEN": "Boron trifluoride", "cas": "7637-07-2", "class": "2.3", "nfpa": {"h": "4", "f": "0", "r": "1", "s": ""},
  {"un": "2417", "nameTW": "氟化羰 (COF2)", "nameEN": "Carbonyl fluoride", "cas": "353-50-4", "class": "2.3", "nfpa": {"h": "4", "f": "0", "r": "1", "s": ""},
  {"un": "2418", "nameTW": "四氟化硫 (SF4)", "nameEN": "Sulfur tetrafluoride", "cas": "7783-60-0", "class": "2.3", "nfpa": {"h": "4", "f": "0", "r": "2", "s": ""},
  {"un": "1040", "nameTW": "環氧乙烷 (EO / 環氧乙烷)", "nameEN": "Ethylene oxide", "cas": "75-21-8", "class": "2.3", "nfpa": {"h": "3", "f": "4", "r": "3", "s": ""},
  {"un": "1835", "nameTW": "氫氧化四甲銨溶液 (TMAH / 顯影液)", "nameEN": "Tetramethylammonium hydroxide sol.", "cas": "75-59-2", "class": "8", "nfpa": {"h": "3", "f": "1", "r": "0", "s": "COR"},
  {"un": "1993", "nameTW": "PGMEA (光阻劑 / 丙二醇甲醚醋酸酯)", "nameEN": "PGMEA", "cas": "108-65-6", "class": "3", "nfpa": {"h": "2", "f": "2", "r": "0", "s": ""},
  {"un": "1292", "nameTW": "四乙氧基矽烷 (TEOS)", "nameEN": "Tetraethyl silicate", "cas": "78-10-4", "class": "3", "nfpa": {"h": "2", "f": "2", "r": "1", "s": ""},
  {"un": "1810", "nameTW": "三氯氧磷 (POCl3)", "nameEN": "Phosphorus oxychloride", "cas": "10025-87-3", "class": "6.1", "nfpa": {"h": "3", "f": "0", "r": "2", "s": "<s>W</s>"},
  {"un": "1741", "nameTW": "三氯化硼 (BCl3)", "nameEN": "Boron trichloride", "cas": "10294-34-5", "class": "2.3", "nfpa": {"h": "4", "f": "0", "r": "2", "s": "<s>W</s>"},
  {"un": "1859", "nameTW": "四氟化矽 (SiF4)", "nameEN": "Silicon tetrafluoride", "cas": "7783-61-1", "class": "2.3", "nfpa": {"h": "3", "f": "0", "r": "2", "s": "<s>W</s>"},
  {"un": "2189", "nameTW": "二氯矽烷 (DCS / 二氯矽甲烷)", "nameEN": "Dichlorosilane", "cas": "4109-96-0", "class": "2.3", "nfpa": {"h": "4", "f": "4", "r": "2", "s": "<s>W</s>"},
  {"un": "1295", "nameTW": "三氯矽烷 (TCS / 三氯矽甲烷)", "nameEN": "Trichlorosilane", "cas": "10025-78-2", "class": "4.3", "nfpa": {"h": "3", "f": "4", "r": "2", "s": "<s>W</s>"},
  {"un": "1070", "nameTW": "一氧化二氮 (N2O / 笑氣)", "nameEN": "Nitrous oxide", "cas": "10024-97-2", "class": "2.2", "nfpa": {"h": "2", "f": "0", "r": "0", "s": "OX"},
  {"un": "2194", "nameTW": "六氟化硒", "nameEN": "Selenium hexafluoride", "cas": "7783-79-1", "class": "2.3", "nfpa": {"h": "4", "f": "0", "r": "0", "s": ""},
  {"un": "2197", "nameTW": "碘化氫 (HI)", "nameEN": "Hydrogen iodide", "cas": "10034-85-2", "class": "2.3", "nfpa": {"h": "3", "f": "0", "r": "1", "s": ""},
  {"un": "2421", "nameTW": "三氧化二氮", "nameEN": "Nitrogen trioxide", "cas": "10544-72-6", "class": "2.3", "nfpa": {"h": "4", "f": "0", "r": "0", "s": "OX"},
  {"un": "1219", "nameTW": "異丙醇 (IPA)", "nameEN": "Isopropanol", "cas": "67-63-0", "class": "3", "nfpa": {"h": "1", "f": "3", "r": "0", "s": ""},
  {"un": "1090", "nameTW": "丙酮 (Acetone)", "nameEN": "Acetone", "cas": "67-64-1", "class": "3", "nfpa": {"h": "1", "f": "3", "r": "0", "s": ""},
  {"un": "1230", "nameTW": "甲醇 (工業酒精 / Methanol)", "nameEN": "Methanol", "cas": "67-56-1", "class": "3", "nfpa": {"h": "3", "f": "3", "r": "0", "s": ""},
  {"un": "1170", "nameTW": "乙醇 (酒精 / Ethanol)", "nameEN": "Ethanol", "cas": "64-17-5", "class": "3", "nfpa": {"h": "0", "f": "3", "r": "0", "s": ""},
  {"un": "1294", "nameTW": "甲苯 (Toluene)", "nameEN": "Toluene", "cas": "108-88-3", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "0", "s": ""},
  {"un": "1307", "nameTW": "二甲苯 (Xylene)", "nameEN": "Xylenes", "cas": "1330-20-7", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "0", "s": ""},
  {"un": "1193", "nameTW": "丁酮 (MEK)", "nameEN": "Ethyl methyl ketone", "cas": "78-93-3", "class": "3", "nfpa": {"h": "1", "f": "3", "r": "0", "s": ""},
  {"un": "1145", "nameTW": "環己烷 (常誤寫為環乙烷)", "nameEN": "Cyclohexane", "cas": "110-82-7", "class": "3", "nfpa": {"h": "1", "f": "3", "r": "0", "s": ""},
  {"un": "1173", "nameTW": "乙酸乙酯 (EA / 醋酸乙酯)", "nameEN": "Ethyl acetate", "cas": "141-78-6", "class": "3", "nfpa": {"h": "1", "f": "3", "r": "0", "s": ""},
  {"un": "1114", "nameTW": "苯 (Benzene)", "nameEN": "Benzene", "cas": "71-43-2", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "0", "s": ""},
  {"un": "2056", "nameTW": "四氫呋喃 (THF)", "nameEN": "Tetrahydrofuran", "cas": "109-99-9", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "1", "s": ""},
  {"un": "1203", "nameTW": "汽油 (無鉛汽油)", "nameEN": "Gasoline", "cas": "86290-81-5", "class": "3", "nfpa": {"h": "1", "f": "3", "r": "0", "s": ""},
  {"un": "1202", "nameTW": "柴油 (重油 / 輕油)", "nameEN": "Diesel fuel", "cas": "68334-30-5", "class": "3", "nfpa": {"h": "0", "f": "2", "r": "0", "s": ""},
  {"un": "1263", "nameTW": "油漆 / 稀釋劑 (香蕉水 / 溶劑)", "nameEN": "Paint", "cas": "N/A", "class": "3", "nfpa": {"h": "1", "f": "3", "r": "0", "s": ""},
  {"un": "2924", "nameTW": "易燃液體腐蝕性 (常見科技廠廢液)", "nameEN": "Flammable liq, corr", "cas": "N/A", "class": "3", "nfpa": {"h": "3", "f": "3", "r": "0", "s": ""},
  {"un": "1992", "nameTW": "易燃液體毒性 (廢液類)", "nameEN": "Flammable liq, toxic", "cas": "N/A", "class": "3", "nfpa": {"h": "3", "f": "3", "r": "0", "s": ""},
  {"un": "2265", "nameTW": "二甲基甲醯胺 (DMF)", "nameEN": "N,N-Dimethylformamide", "cas": "68-12-2", "class": "3", "nfpa": {"h": "2", "f": "2", "r": "0", "s": ""},
  {"un": "1120", "nameTW": "丁醇 (Butanol)", "nameEN": "Butanols", "cas": "71-36-3", "class": "3", "nfpa": {"h": "1", "f": "3", "r": "0", "s": ""},
  {"un": "1280", "nameTW": "環氧丙烷", "nameEN": "Propylene oxide", "cas": "75-56-9", "class": "3", "nfpa": {"h": "3", "f": "4", "r": "2", "s": ""},
  {"un": "1866", "nameTW": "樹脂溶液 (Resin / EPOXY)", "nameEN": "Resin solution", "cas": "N/A", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "0", "s": ""},
  {"un": "1131", "nameTW": "二硫化碳 (CS2)", "nameEN": "Carbon disulfide", "cas": "75-15-0", "class": "3", "nfpa": {"h": "3", "f": "4", "r": "0", "s": ""},
  {"un": "1165", "nameTW": "二氧六烷 (1,4-二噁烷)", "nameEN": "Dioxane", "cas": "123-91-1", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "1", "s": ""},
  {"un": "1206", "nameTW": "正庚烷", "nameEN": "Heptanes", "cas": "142-82-5", "class": "3", "nfpa": {"h": "1", "f": "3", "r": "0", "s": ""},
  {"un": "1208", "nameTW": "正己烷", "nameEN": "Hexanes", "cas": "110-54-3", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "0", "s": ""},
  {"un": "1212", "nameTW": "異丁醇", "nameEN": "Isobutanol", "cas": "78-83-1", "class": "3", "nfpa": {"h": "1", "f": "3", "r": "0", "s": ""},
  {"un": "1213", "nameTW": "醋酸異丁酯", "nameEN": "Isobutyl acetate", "cas": "110-19-0", "class": "3", "nfpa": {"h": "1", "f": "3", "r": "0", "s": ""},
  {"un": "1262", "nameTW": "辛烷", "nameEN": "Octanes", "cas": "111-65-9", "class": "3", "nfpa": {"h": "0", "f": "3", "r": "0", "s": ""},
  {"un": "1123", "nameTW": "乙酸丁酯", "nameEN": "Butyl acetates", "cas": "123-86-4", "class": "3", "nfpa": {"h": "1", "f": "3", "r": "0", "s": ""},
  {"un": "1104", "nameTW": "乙酸戊酯", "nameEN": "Amyl acetates", "cas": "628-63-7", "class": "3", "nfpa": {"h": "1", "f": "3", "r": "0", "s": ""},
  {"un": "1301", "nameTW": "醋酸乙烯酯 (VAM)", "nameEN": "Vinyl acetate", "cas": "108-05-4", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "2", "s": ""},
  {"un": "1154", "nameTW": "二乙胺", "nameEN": "Diethylamine", "cas": "109-89-7", "class": "3", "nfpa": {"h": "3", "f": "3", "r": "0", "s": ""},
  {"un": "1160", "nameTW": "二甲胺溶液", "nameEN": "Dimethylamine sol.", "cas": "124-40-3", "class": "3", "nfpa": {"h": "3", "f": "3", "r": "0", "s": ""},
  {"un": "1184", "nameTW": "二氯乙烷", "nameEN": "Ethylene dichloride", "cas": "107-06-2", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "0", "s": ""},
  {"un": "2029", "nameTW": "聯胺 (無水)", "nameEN": "Hydrazine, anhydrous", "cas": "302-01-2", "class": "3", "nfpa": {"h": "4", "f": "3", "r": "2", "s": ""},
  {"un": "1133", "nameTW": "膠水 (接著劑 / 強力膠)", "nameEN": "Adhesives", "cas": "N/A", "class": "3", "nfpa": {"h": "1", "f": "3", "r": "0", "s": ""},
  {"un": "1790", "nameTW": "氫氟酸 (化骨水 / 氟化氫水溶液)", "nameEN": "Hydrofluoric acid", "cas": "7664-39-3", "class": "8", "nfpa": {"h": "4", "f": "0", "r": "1", "s": "COR"},
  {"un": "2031", "nameTW": "硝酸 (混酸 / 強酸)", "nameEN": "Nitric acid", "cas": "7697-37-2", "class": "8", "nfpa": {"h": "4", "f": "0", "r": "0", "s": "OX"},
  {"un": "1830", "nameTW": "硫酸 (濃硫酸)", "nameEN": "Sulfuric acid", "cas": "7664-93-9", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "2", "s": "<s>W</s>"},
  {"un": "1789", "nameTW": "鹽酸 (氯化氫水溶液)", "nameEN": "Hydrochloric acid", "cas": "7647-01-0", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "0", "s": "COR"},
  {"un": "1823", "nameTW": "氫氧化鈉 (片鹼 / 液鹼)", "nameEN": "Sodium hydroxide", "cas": "1310-73-2", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "1", "s": "COR"},
  {"un": "2672", "nameTW": "氨水 (氫氧化銨溶液)", "nameEN": "Ammonia solution", "cas": "1336-21-6", "class": "8", "nfpa": {"h": "3", "f": "1", "r": "0", "s": "COR"},
  {"un": "1791", "nameTW": "次氯酸鈉 (漂白水)", "nameEN": "Sodium hypochlorite", "cas": "7681-52-9", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "1", "s": ""},
  {"un": "2014", "nameTW": "雙氧水 (過氧化氫溶液 20-60%)", "nameEN": "Hydrogen peroxide", "cas": "7722-84-1", "class": "5.1", "nfpa": {"h": "3", "f": "0", "r": "1", "s": "OX"},
  {"un": "2015", "nameTW": "高濃度雙氧水 (>60%)", "nameEN": "Hydrogen peroxide, stab.", "cas": "7722-84-1", "class": "5.1", "nfpa": {"h": "3", "f": "0", "r": "3", "s": "OX"},
  {"un": "1805", "nameTW": "磷酸", "nameEN": "Phosphoric acid", "cas": "7664-38-2", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "0", "s": "COR"},
  {"un": "1802", "nameTW": "高氯酸 (過氯酸)", "nameEN": "Perchloric acid", "cas": "7601-90-3", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "3", "s": "OX"},
  {"un": "1829", "nameTW": "三氧化硫", "nameEN": "Sulfur trioxide", "cas": "7446-11-9", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "2", "s": "<s>W</s>"},
  {"un": "1715", "nameTW": "乙酸酐 (醋酸酐)", "nameEN": "Acetic anhydride", "cas": "108-24-7", "class": "8", "nfpa": {"h": "3", "f": "2", "r": "1", "s": "<s>W</s>"},
  {"un": "2789", "nameTW": "冰醋酸 (冰乙酸)", "nameEN": "Glacial acetic acid", "cas": "64-19-7", "class": "8", "nfpa": {"h": "3", "f": "2", "r": "0", "s": "COR"},
  {"un": "1848", "nameTW": "丙酸", "nameEN": "Propionic acid", "cas": "79-09-4", "class": "8", "nfpa": {"h": "3", "f": "2", "r": "0", "s": ""},
  {"un": "2259", "nameTW": "三乙烯四胺 (TETA / 固化劑)", "nameEN": "Triethylenetetramine", "cas": "112-24-3", "class": "8", "nfpa": {"h": "3", "f": "1", "r": "0", "s": ""},
  {"un": "2491", "nameTW": "乙醇胺", "nameEN": "Ethanolamine", "cas": "141-43-5", "class": "8", "nfpa": {"h": "3", "f": "1", "r": "0", "s": ""},
  {"un": "1604", "nameTW": "乙二胺", "nameEN": "Ethylenediamine", "cas": "107-15-3", "class": "8", "nfpa": {"h": "3", "f": "2", "r": "0", "s": ""},
  {"un": "1428", "nameTW": "金屬鈉 (Na)", "nameEN": "Sodium", "cas": "7440-23-5", "class": "4.3", "nfpa": {"h": "3", "f": "3", "r": "2", "s": "<s>W</s>"},
  {"un": "1415", "nameTW": "金屬鋰 (Li)", "nameEN": "Lithium", "cas": "7439-93-2", "class": "4.3", "nfpa": {"h": "3", "f": "2", "r": "2", "s": "<s>W</s>"},
  {"un": "1420", "nameTW": "金屬鉀 (K)", "nameEN": "Potassium", "cas": "7440-09-7", "class": "4.3", "nfpa": {"h": "3", "f": "3", "r": "2", "s": "<s>W</s>"},
  {"un": "1418", "nameTW": "鎂粉 (Mg)", "nameEN": "Magnesium powder", "cas": "7439-95-4", "class": "4.3", "nfpa": {"h": "0", "f": "1", "r": "1", "s": "<s>W</s>"},
  {"un": "1396", "nameTW": "鋁粉 (Al)", "nameEN": "Aluminum powder", "cas": "7429-90-5", "class": "4.3", "nfpa": {"h": "0", "f": "1", "r": "1", "s": "<s>W</s>"},
  {"un": "1402", "nameTW": "電石 (碳化鈣 / 碳化鎢)", "nameEN": "Calcium carbide", "cas": "75-20-7", "class": "4.3", "nfpa": {"h": "3", "f": "4", "r": "2", "s": "<s>W</s>"},
  {"un": "1411", "nameTW": "氫化鋁鋰 (LAH)", "nameEN": "Lithium aluminum hydride", "cas": "16853-85-3", "class": "4.3", "nfpa": {"h": "3", "f": "2", "r": "2", "s": "<s>W</s>"},
  {"un": "1431", "nameTW": "甲醇鈉", "nameEN": "Sodium methylate", "cas": "124-41-4", "class": "4.2", "nfpa": {"h": "3", "f": "3", "r": "2", "s": "<s>W</s>"},
  {"un": "3051", "nameTW": "三乙基鋁 (TEAL)", "nameEN": "Triethylaluminum", "cas": "97-93-8", "class": "4.2", "nfpa": {"h": "3", "f": "4", "r": "3", "s": "<s>W</s>"},
  {"un": "3394", "nameTW": "烷基鋰 (自燃禁水液體)", "nameEN": "Pyrophoric liquid", "cas": "N/A", "class": "4.2", "nfpa": {"h": "3", "f": "4", "r": "3", "s": "<s>W</s>"},
  {"un": "3399", "nameTW": "有機金屬禁水液體", "nameEN": "Organometallic liq.", "cas": "N/A", "class": "4.3", "nfpa": {"h": "3", "f": "4", "r": "2", "s": "<s>W</s>"},
  {"un": "6000", "nameTW": "磷化鋁 (農藥 / 燻蒸劑)", "nameEN": "Aluminum phosphide", "cas": "20859-73-8", "class": "4.3", "nfpa": {"h": "4", "f": "4", "r": "2", "s": "<s>W</s>"},
  {"un": "1689", "nameTW": "氰化鈉 (青化鈉)", "nameEN": "Sodium cyanide", "cas": "143-33-9", "class": "6.1", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "1547", "nameTW": "苯胺 (Aniline)", "nameEN": "Aniline", "cas": "62-53-3", "class": "6.1", "nfpa": {"h": "3", "f": "2", "r": "0", "s": ""},
  {"un": "1671", "nameTW": "苯酚 (石炭酸 / Phenol)", "nameEN": "Phenol, solid", "cas": "108-95-2", "class": "6.1", "nfpa": {"h": "3", "f": "2", "r": "0", "s": ""},
  {"un": "2078", "nameTW": "甲苯二異氰酸酯 (TDI)", "nameEN": "Toluene diisocyanate", "cas": "584-84-9", "class": "6.1", "nfpa": {"h": "3", "f": "1", "r": "1", "s": ""},
  {"un": "2810", "nameTW": "毒性液體 (未指明化學品)", "nameEN": "Toxic liquid, nos", "cas": "N/A", "class": "6.1", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "2811", "nameTW": "毒性固體 (未指明化學品)", "nameEN": "Toxic solid, nos", "cas": "N/A", "class": "6.1", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "3101", "nameTW": "過氧化苯甲醯 (BPO / 硬化劑)", "nameEN": "Benzoyl peroxide", "cas": "94-36-0", "class": "5.2", "nfpa": {"h": "1", "f": "3", "r": "4", "s": ""},
  {"un": "3105", "nameTW": "有機過氧化物D型", "nameEN": "Organic peroxide D", "cas": "N/A", "class": "5.2", "nfpa": {"h": "2", "f": "3", "r": "2", "s": ""},
  {"un": "3221", "nameTW": "偶氮二異丁腈 (AIBN)", "nameEN": "AIBN", "cas": "78-67-1", "class": "4.1", "nfpa": {"h": "1", "f": "3", "r": "3", "s": ""},
  {"un": "1490", "nameTW": "高錳酸鉀 (過錳酸鉀)", "nameEN": "Potassium permanganate", "cas": "7722-64-7", "class": "5.1", "nfpa": {"h": "1", "f": "0", "r": "0", "s": "OX"},
  {"un": "1496", "nameTW": "亞氯酸鈉", "nameEN": "Sodium chlorite", "cas": "7758-19-2", "class": "5.1", "nfpa": {"h": "2", "f": "0", "r": "1", "s": "OX"},
  {"un": "1500", "nameTW": "亞硝酸鈉", "nameEN": "Sodium nitrite", "cas": "7632-00-0", "class": "5.1", "nfpa": {"h": "3", "f": "0", "r": "1", "s": "OX"},
  {"un": "2448", "nameTW": "硫磺 (熔融態)", "nameEN": "Sulfur, molten", "cas": "7704-34-9", "class": "4.1", "nfpa": {"h": "2", "f": "1", "r": "0", "s": ""},
  {"un": "2211", "nameTW": "聚苯乙烯珠 (保麗龍原料)", "nameEN": "Polymeric beads", "cas": "N/A", "class": "9", "nfpa": {"h": "1", "f": "2", "r": "0", "s": ""},
  {"un": "3082", "nameTW": "危害環境液體 (廢水類)", "nameEN": "Env. hazardous liq.", "cas": "N/A", "class": "9", "nfpa": {"h": "1", "f": "1", "r": "0", "s": ""},
  {"un": "1648", "nameTW": "乙腈 (ACN / 甲基氰 / 乙晴)", "nameEN": "Acetonitrile", "cas": "75-05-8", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "0", "s": ""},
  {"un": "1245", "nameTW": "甲基異丁基酮 (MIBK)", "nameEN": "Methyl isobutyl ketone", "cas": "108-10-1", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "0", "s": ""},
  {"un": "1593", "nameTW": "二氯甲烷 (DCM / 氯甲烷 / 退漆劑)", "nameEN": "Dichloromethane", "cas": "75-09-2", "class": "6.1", "nfpa": {"h": "2", "f": "1", "r": "0", "s": ""},
  {"un": "1888", "nameTW": "氯仿 (三氯甲烷 / Chloroform)", "nameEN": "Chloroform", "cas": "67-66-3", "class": "6.1", "nfpa": {"h": "2", "f": "0", "r": "0", "s": ""},
  {"un": "1710", "nameTW": "三氯乙烯 (TCE / 洗板劑 / 脫脂劑)", "nameEN": "Trichloroethylene", "cas": "79-01-6", "class": "6.1", "nfpa": {"h": "2", "f": "1", "r": "0", "s": ""},
  {"un": "1155", "nameTW": "乙醚 (二乙醚 / 乙基醚 / 麻醉醚)", "nameEN": "Diethyl ether", "cas": "60-29-7", "class": "3", "nfpa": {"h": "1", "f": "4", "r": "1", "s": ""},
  {"un": "1089", "nameTW": "乙醛 (Acetaldehyde)", "nameEN": "Acetaldehyde", "cas": "75-07-0", "class": "3", "nfpa": {"h": "2", "f": "4", "r": "2", "s": ""},
  {"un": "1247", "nameTW": "甲基丙烯酸甲酯 (MMA / 壓克力單體)", "nameEN": "Methyl methacrylate", "cas": "80-62-6", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "2", "s": ""},
  {"un": "2055", "nameTW": "苯乙烯單體 (SM / 苯乙烯 / Styrene)", "nameEN": "Styrene monomer", "cas": "100-42-5", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "2", "s": ""},
  {"un": "1198", "nameTW": "福馬林 (甲醛溶液 / Formalin)", "nameEN": "Formaldehyde solution", "cas": "50-00-0", "class": "3", "nfpa": {"h": "3", "f": "2", "r": "0", "s": ""},
  {"un": "1942", "nameTW": "硝酸銨 (硝銨 / 肥料炸彈原料)", "nameEN": "Ammonium nitrate", "cas": "6484-52-2", "class": "5.1", "nfpa": {"h": "2", "f": "0", "r": "3", "s": "OX"},
  {"un": "1680", "nameTW": "氰化鉀 (KCN / 山埃)", "nameEN": "Potassium cyanide", "cas": "151-50-8", "class": "6.1", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "2202", "nameTW": "硒化氫 (H2Se / 硒烷)", "nameEN": "Hydrogen selenide", "cas": "7783-07-5", "class": "2.3", "nfpa": {"h": "4", "f": "4", "r": "0", "s": ""},
  {"un": "1079", "nameTW": "二氧化硫 (SO2)", "nameEN": "Sulfur dioxide", "cas": "7446-09-5", "class": "2.3", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "1660", "nameTW": "一氧化氮 (NO / 氧化氮)", "nameEN": "Nitric oxide", "cas": "10102-43-9", "class": "2.3", "nfpa": {"h": "3", "f": "0", "r": "0", "s": "OX"},
  {"un": "1045", "nameTW": "氟氣 (氟 / F2)", "nameEN": "Fluorine", "cas": "7782-41-4", "class": "2.3", "nfpa": {"h": "4", "f": "0", "r": "3", "s": "W,OX"},
  {"un": "1754", "nameTW": "氯磺酸", "nameEN": "Chlorosulfonic acid", "cas": "7790-94-5", "class": "8", "nfpa": {"h": "4", "f": "0", "r": "2", "s": "<s>W</s>"},
  {"un": "2023", "nameTW": "環氧氯丙烷 (ECH / 表氯醇)", "nameEN": "Epichlorohydrin", "cas": "106-89-8", "class": "6.1", "nfpa": {"h": "3", "f": "3", "r": "2", "s": ""},
  {"un": "2218", "nameTW": "丙烯酸 (冰丙烯酸)", "nameEN": "Acrylic acid", "cas": "79-10-7", "class": "8", "nfpa": {"h": "3", "f": "2", "r": "2", "s": ""},
  {"un": "2822", "nameTW": "吡啶 (Pyridine / 臭味劑)", "nameEN": "Pyridine", "cas": "110-86-1", "class": "3", "nfpa": {"h": "3", "f": "3", "r": "0", "s": ""},
  {"un": "2076", "nameTW": "甲酚 (煤酚 / Cresol)", "nameEN": "Cresols", "cas": "1319-77-3", "class": "6.1", "nfpa": {"h": "3", "f": "2", "r": "0", "s": ""},
  {"un": "1897", "nameTW": "四氯乙烯 (PCE / 乾洗油)", "nameEN": "Tetrachloroethylene", "cas": "127-18-4", "class": "6.1", "nfpa": {"h": "2", "f": "0", "r": "0", "s": ""},
  {"un": "2781", "nameTW": "巴拉刈 (Paraquat / 固殺草 / 除草劑)", "nameEN": "Bipyridilium pesticide", "cas": "1910-42-5", "class": "6.1", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "1048", "nameTW": "溴化氫 (無水 / HBr)", "nameEN": "Hydrogen bromide", "cas": "10035-10-6", "class": "2.3", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "3286", "nameTW": "HMDS (六甲基二矽氮烷 / 增黏劑)", "nameEN": "Hexamethyldisilazane", "cas": "999-97-3", "class": "3", "nfpa": {"h": "3", "f": "3", "r": "1", "s": ""},
  {"un": "1982", "nameTW": "四氟化碳 (CF4 / 氟里昂14)", "nameEN": "Tetrafluoromethane", "cas": "75-73-0", "class": "2.2", "nfpa": {"h": "1", "f": "0", "r": "0", "s": ""},
  {"un": "1984", "nameTW": "三氟甲烷 (CHF3 / 氟里昂23)", "nameEN": "Trifluoromethane", "cas": "75-46-7", "class": "2.2", "nfpa": {"h": "2", "f": "0", "r": "0", "s": ""},
  {"un": "2193", "nameTW": "六氟乙烷 (C2F6 / 氟里昂116)", "nameEN": "Hexafluoroethane", "cas": "76-16-4", "class": "2.2", "nfpa": {"h": "2", "f": "0", "r": "0", "s": ""},
  {"un": "1976", "nameTW": "八氟環丁烷 (C4F8 / 氟里昂C318)", "nameEN": "Octafluorocyclobutane", "cas": "115-25-3", "class": "2.2", "nfpa": {"h": "2", "f": "0", "r": "0", "s": ""},
  {"un": "2204", "nameTW": "硫化羰 (COS / 氧硫化碳)", "nameEN": "Carbonyl sulfide", "cas": "463-58-1", "class": "2.3", "nfpa": {"h": "3", "f": "4", "r": "1", "s": ""},
  {"un": "1859", "nameTW": "四氟化矽 (SiF4 / 氟化矽)", "nameEN": "Silicon tetrafluoride", "cas": "7783-61-1", "class": "2.3", "nfpa": {"h": "3", "f": "0", "r": "2", "s": "<s>W</s>"},
  {"un": "2189", "nameTW": "二氯矽烷 (DCS / 二氯矽甲烷)", "nameEN": "Dichlorosilane", "cas": "4109-96-0", "class": "2.3", "nfpa": {"h": "4", "f": "4", "r": "2", "s": "<s>W</s>"},
  {"un": "1295", "nameTW": "三氯矽烷 (TCS / 三氯矽甲烷)", "nameEN": "Trichlorosilane", "cas": "10025-78-2", "class": "4.3", "nfpa": {"h": "3", "f": "4", "r": "2", "s": "<s>W</s>"},
  {"un": "1818", "nameTW": "四氯化矽 (STC / 氯化矽)", "nameEN": "Silicon tetrachloride", "cas": "10026-04-7", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "2", "s": "<s>W</s>"},
  {"un": "1741", "nameTW": "三氯化硼 (BCl3 / 氯化硼)", "nameEN": "Boron trichloride", "cas": "10294-34-5", "class": "2.3", "nfpa": {"h": "4", "f": "0", "r": "2", "s": "<s>W</s>"},
  {"un": "1008", "nameTW": "三氟化硼 (BF3 / 氟化硼)", "nameEN": "Boron trifluoride", "cas": "7637-07-2", "class": "2.3", "nfpa": {"h": "4", "f": "0", "r": "1", "s": ""},
  {"un": "2692", "nameTW": "三溴化硼 (BBr3)", "nameEN": "Boron tribromide", "cas": "10294-33-4", "class": "8", "nfpa": {"h": "4", "f": "0", "r": "2", "s": "<s>W</s>"},
  {"un": "1810", "nameTW": "三氯氧磷 (POCl3 / 磷酸三氯 / 液態磷)", "nameEN": "Phosphorus oxychloride", "cas": "10025-87-3", "class": "6.1", "nfpa": {"h": "3", "f": "0", "r": "2", "s": "<s>W</s>"},
  {"un": "1911", "nameTW": "乙硼烷 (B2H6 / 二硼烷)", "nameEN": "Diborane", "cas": "19237-62-4", "class": "2.3", "nfpa": {"h": "4", "f": "4", "r": "3", "s": "<s>W</s>"},
  {"un": "2192", "nameTW": "鍺烷 (GeH4 / 鍺化氫)", "nameEN": "Germane", "cas": "7782-65-2", "class": "2.3", "nfpa": {"h": "4", "f": "4", "r": "1", "s": ""},
  {"un": "2188", "nameTW": "砷化氫 (AsH3 / 胂 / 砷烷)", "nameEN": "Arsine", "cas": "7784-42-1", "class": "2.3", "nfpa": {"h": "4", "f": "4", "r": "2", "s": ""},
  {"un": "2199", "nameTW": "磷化氫 (PH3 / 磷烷)", "nameEN": "Phosphine", "cas": "7803-51-2", "class": "2.3", "nfpa": {"h": "4", "f": "4", "r": "2", "s": ""},
  {"un": "2202", "nameTW": "硒化氫 (H2Se / 硒烷)", "nameEN": "Hydrogen selenide", "cas": "7783-07-5", "class": "2.3", "nfpa": {"h": "4", "f": "4", "r": "0", "s": ""},
  {"un": "2196", "nameTW": "六氟化鎢 (WF6)", "nameEN": "Tungsten hexafluoride", "cas": "7783-82-6", "class": "2.3", "nfpa": {"h": "4", "f": "0", "r": "1", "s": ""},
  {"un": "1048", "nameTW": "溴化氫 (HBr / 無水氫溴酸)", "nameEN": "Hydrogen bromide", "cas": "10035-10-6", "class": "2.3", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "1050", "nameTW": "氯化氫 (HCl / 無水鹽酸氣)", "nameEN": "Hydrogen chloride", "cas": "7647-01-0", "class": "2.3", "nfpa": {"h": "3", "f": "0", "r": "1", "s": ""},
  {"un": "1749", "nameTW": "三氟化氯 (ClF3 / 洗管氣 / 燃燒玻璃)", "nameEN": "Chlorine trifluoride", "cas": "7790-91-2", "class": "2.3", "nfpa": {"h": "4", "f": "0", "r": "3", "s": "W,OX"},
  {"un": "1045", "nameTW": "氟氣 (F2 / 氟)", "nameEN": "Fluorine", "cas": "7782-41-4", "class": "2.3", "nfpa": {"h": "4", "f": "0", "r": "3", "s": "W,OX"},
  {"un": "1660", "nameTW": "一氧化氮 (NO / 氧化氮)", "nameEN": "Nitric oxide", "cas": "10102-43-9", "class": "2.3", "nfpa": {"h": "3", "f": "0", "r": "0", "s": "OX"},
  {"un": "1067", "nameTW": "二氧化氮 (NO2 / 四氧化二氮)", "nameEN": "Nitrogen dioxide", "cas": "10102-44-0", "class": "2.3", "nfpa": {"h": "3", "f": "0", "r": "0", "s": "OX"},
  {"un": "2451", "nameTW": "三氟化氮 (NF3 / 洗管氣)", "nameEN": "Nitrogen trifluoride", "cas": "7783-54-2", "class": "2.2", "nfpa": {"h": "1", "f": "0", "r": "0", "s": "OX"},
  {"un": "2421", "nameTW": "三氧化二氮 (N2O3)", "nameEN": "Nitrogen trioxide", "cas": "10544-72-6", "class": "2.3", "nfpa": {"h": "4", "f": "0", "r": "0", "s": "OX"},
  {"un": "2194", "nameTW": "六氟化硒 (SeF6)", "nameEN": "Selenium hexafluoride", "cas": "7783-79-1", "class": "2.3", "nfpa": {"h": "4", "f": "0", "r": "0", "s": ""},
  {"un": "2417", "nameTW": "氟化羰 (COF2 / 氟化碳醯)", "nameEN": "Carbonyl fluoride", "cas": "353-50-4", "class": "2.3", "nfpa": {"h": "4", "f": "0", "r": "1", "s": ""},
  {"un": "2418", "nameTW": "四氟化硫 (SF4)", "nameEN": "Sulfur tetrafluoride", "cas": "7783-60-0", "class": "2.3", "nfpa": {"h": "4", "f": "0", "r": "2", "s": ""},
  {"un": "3394", "nameTW": "三甲基鎵 (TMG / TMGa / 烷基金屬)", "nameEN": "Trimethylgallium", "cas": "1445-79-0", "class": "4.2", "nfpa": {"h": "3", "f": "4", "r": "3", "s": "<s>W</s>"},
  {"un": "3394", "nameTW": "三甲基銦 (TMI / TMIn)", "nameEN": "Trimethylindium", "cas": "3385-78-2", "class": "4.2", "nfpa": {"h": "3", "f": "4", "r": "3", "s": "<s>W</s>"},
  {"un": "3394", "nameTW": "三甲基鋁 (TMA / TMAl)", "nameEN": "Trimethylaluminum", "cas": "75-24-1", "class": "4.2", "nfpa": {"h": "3", "f": "4", "r": "3", "s": "<s>W</s>"},
  {"un": "3051", "nameTW": "三乙基鋁 (TEAL / TEAl)", "nameEN": "Triethylaluminum", "cas": "97-93-8", "class": "4.2", "nfpa": {"h": "3", "f": "4", "r": "3", "s": "<s>W</s>"},
  {"un": "3394", "nameTW": "二乙基鋅 (DEZ / DEZn)", "nameEN": "Diethylzinc", "cas": "557-20-0", "class": "4.2", "nfpa": {"h": "3", "f": "4", "r": "3", "s": "<s>W</s>"},
  {"un": "3394", "nameTW": "二甲基鋅 (DMZ / DMZn)", "nameEN": "Dimethylzinc", "cas": "544-97-8", "class": "4.2", "nfpa": {"h": "3", "f": "4", "r": "3", "s": "<s>W</s>"},
  {"un": "3399", "nameTW": "二茂鎂 (Cp2Mg / 金屬有機液體)", "nameEN": "Bis(cyclopentadienyl)magnesium", "cas": "1284-72-6", "class": "4.3", "nfpa": {"h": "3", "f": "4", "r": "2", "s": "<s>W</s>"},
  {"un": "3399", "nameTW": "四甲基錫 (TMT / 金屬有機物)", "nameEN": "Tetramethyltin", "cas": "594-27-4", "class": "4.3", "nfpa": {"h": "3", "f": "4", "r": "2", "s": "<s>W</s>"},
  {"un": "3398", "nameTW": "正丁基鋰 (n-BuLi / 烷基鋰)", "nameEN": "n-Butyllithium", "cas": "109-72-8", "class": "4.2", "nfpa": {"h": "3", "f": "4", "r": "3", "s": "<s>W</s>"},
  {"un": "3392", "nameTW": "三級丁基鋰 (t-BuLi / 烷基鋰)", "nameEN": "tert-Butyllithium", "cas": "594-19-4", "class": "4.2", "nfpa": {"h": "3", "f": "4", "r": "3", "s": "<s>W</s>"},
  {"un": "2265", "nameTW": "N,N-二甲基甲醯胺 (DMF / 二甲基甲醯胺)", "nameEN": "N,N-Dimethylformamide", "cas": "68-12-2", "class": "3", "nfpa": {"h": "2", "f": "2", "r": "0", "s": ""},
  {"un": "1993", "nameTW": "N-甲基-2-吡咯烷酮 (NMP / 去光阻液)", "nameEN": "N-Methyl-2-pyrrolidone", "cas": "872-50-4", "class": "3", "nfpa": {"h": "2", "f": "1", "r": "0", "s": ""},
  {"un": "1993", "nameTW": "GBL (γ-丁內酯 / 伽瑪丁內酯)", "nameEN": "gamma-Butyrolactone", "cas": "96-48-0", "class": "3", "nfpa": {"h": "2", "f": "1", "r": "0", "s": ""},
  {"un": "1993", "nameTW": "二甲亞碸 (DMSO / 去光阻液)", "nameEN": "Dimethyl sulfoxide", "cas": "67-68-5", "class": "3", "nfpa": {"h": "1", "f": "1", "r": "0", "s": ""},
  {"un": "1993", "nameTW": "PGMEA (PMA / 丙二醇甲醚醋酸酯 / 光阻劑)", "nameEN": "PGMEA", "cas": "108-65-6", "class": "3", "nfpa": {"h": "2", "f": "2", "r": "0", "s": ""},
  {"un": "3092", "nameTW": "PGME (丙二醇單甲醚 / PM)", "nameEN": "1-Methoxy-2-propanol", "cas": "107-98-2", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "0", "s": ""},
  {"un": "1192", "nameTW": "乳酸乙酯 (Ethyl lactate / EBR)", "nameEN": "Ethyl lactate", "cas": "97-64-3", "class": "3", "nfpa": {"h": "2", "f": "2", "r": "0", "s": ""},
  {"un": "2245", "nameTW": "環戊酮 (Cyclopentanone / 去光阻液)", "nameEN": "Cyclopentanone", "cas": "120-92-3", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "0", "s": ""},
  {"un": "1993", "nameTW": "NEP (N-乙基吡咯烷酮 / NMP替代品)", "nameEN": "N-Ethyl-2-pyrrolidone", "cas": "2687-91-4", "class": "3", "nfpa": {"h": "2", "f": "1", "r": "0", "s": ""},
  {"un": "1292", "nameTW": "四乙氧基矽烷 (TEOS / 矽酸四乙酯)", "nameEN": "Tetraethyl silicate", "cas": "78-10-4", "class": "3", "nfpa": {"h": "2", "f": "2", "r": "1", "s": ""},
  {"un": "1993", "nameTW": "HMDS (六甲基二矽氮烷 / 增黏劑)", "nameEN": "Hexamethyldisilazane", "cas": "999-97-3", "class": "3", "nfpa": {"h": "3", "f": "3", "r": "1", "s": ""},
  {"un": "1824", "nameTW": "氫氧化鉀溶液 (KOH / 液鹼 / 顯影液)", "nameEN": "Potassium hydroxide sol.", "cas": "1310-58-3", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "1", "s": "COR"},
  {"un": "2817", "nameTW": "BOE (緩衝氧化物蝕刻液 / 含氫氟酸)", "nameEN": "Buffered Oxide Etch / Ammonium hydrogendifluoride sol.", "cas": "N/A", "class": "8", "nfpa": {"h": "4", "f": "0", "r": "1", "s": ""},
  {"un": "2924", "nameTW": "去光阻廢液 (Flammable, corrosive)", "nameEN": "Stripper waste", "cas": "N/A", "class": "3", "nfpa": {"h": "3", "f": "3", "r": "0", "s": ""},
  {"un": "1648", "nameTW": "乙腈 (ACN / 甲基氰 / 乙晴)", "nameEN": "Acetonitrile", "cas": "75-05-8", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "0", "s": ""},
  {"un": "1245", "nameTW": "甲基異丁基酮 (MIBK)", "nameEN": "Methyl isobutyl ketone", "cas": "108-10-1", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "0", "s": ""},
  {"un": "1593", "nameTW": "二氯甲烷 (DCM / 氯甲烷 / 退漆劑)", "nameEN": "Dichloromethane", "cas": "75-09-2", "class": "6.1", "nfpa": {"h": "2", "f": "1", "r": "0", "s": ""},
  {"un": "1888", "nameTW": "氯仿 (三氯甲烷 / Chloroform)", "nameEN": "Chloroform", "cas": "67-66-3", "class": "6.1", "nfpa": {"h": "2", "f": "0", "r": "0", "s": ""},
  {"un": "1710", "nameTW": "三氯乙烯 (TCE / 洗板劑 / 脫脂劑)", "nameEN": "Trichloroethylene", "cas": "79-01-6", "class": "6.1", "nfpa": {"h": "2", "f": "1", "r": "0", "s": ""},
  {"un": "1155", "nameTW": "乙醚 (二乙醚 / 麻醉醚 / 乙基醚)", "nameEN": "Diethyl ether", "cas": "60-29-7", "class": "3", "nfpa": {"h": "1", "f": "4", "r": "1", "s": ""},
  {"un": "1089", "nameTW": "乙醛 (Acetaldehyde)", "nameEN": "Acetaldehyde", "cas": "75-07-0", "class": "3", "nfpa": {"h": "2", "f": "4", "r": "2", "s": ""},
  {"un": "1198", "nameTW": "福馬林 (甲醛溶液 / Formalin / 防腐劑)", "nameEN": "Formaldehyde solution", "cas": "50-00-0", "class": "3", "nfpa": {"h": "3", "f": "2", "r": "0", "s": ""},
  {"un": "2822", "nameTW": "吡啶 (Pyridine / 臭味劑)", "nameEN": "Pyridine", "cas": "110-86-1", "class": "3", "nfpa": {"h": "3", "f": "3", "r": "0", "s": ""},
  {"un": "1897", "nameTW": "四氯乙烯 (PCE / 乾洗油)", "nameEN": "Tetrachloroethylene", "cas": "127-18-4", "class": "6.1", "nfpa": {"h": "2", "f": "0", "r": "0", "s": ""},
  {"un": "2264", "nameTW": "二甲基環己胺 (DMCHA / 發泡催化劑)", "nameEN": "N,N-Dimethylcyclohexylamine", "cas": "98-94-2", "class": "8", "nfpa": {"h": "3", "f": "2", "r": "0", "s": ""},
  {"un": "2491", "nameTW": "二乙醇胺 (DEA)", "nameEN": "Diethanolamine", "cas": "111-42-2", "class": "8", "nfpa": {"h": "1", "f": "1", "r": "0", "s": ""},
  {"un": "2076", "nameTW": "甲酚 (煤酚 / Cresol / 消毒劑原料)", "nameEN": "Cresols", "cas": "1319-77-3", "class": "6.1", "nfpa": {"h": "3", "f": "2", "r": "0", "s": ""},
  {"un": "2810", "nameTW": "異佛爾酮 (Isophorone)", "nameEN": "Isophorone", "cas": "78-59-1", "class": "6.1", "nfpa": {"h": "2", "f": "2", "r": "0", "s": ""},
  {"un": "1915", "nameTW": "環己酮 (Cyclohexanone)", "nameEN": "Cyclohexanone", "cas": "108-94-1", "class": "3", "nfpa": {"h": "1", "f": "2", "r": "0", "s": ""},
  {"un": "1247", "nameTW": "甲基丙烯酸甲酯 (MMA / 壓克力單體)", "nameEN": "Methyl methacrylate", "cas": "80-62-6", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "2", "s": ""},
  {"un": "2055", "nameTW": "苯乙烯單體 (SM / 苯乙烯 / Styrene)", "nameEN": "Styrene monomer", "cas": "100-42-5", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "2", "s": ""},
  {"un": "2218", "nameTW": "丙烯酸 (冰丙烯酸 / 壓克力酸)", "nameEN": "Acrylic acid", "cas": "79-10-7", "class": "8", "nfpa": {"h": "3", "f": "2", "r": "2", "s": ""},
  {"un": "1086", "nameTW": "氯乙烯單體 (VCM)", "nameEN": "Vinyl chloride", "cas": "75-01-4", "class": "2.1", "nfpa": {"h": "2", "f": "4", "r": "2", "s": ""},
  {"un": "2023", "nameTW": "環氧氯丙烷 (ECH / 表氯醇)", "nameEN": "Epichlorohydrin", "cas": "106-89-8", "class": "6.1", "nfpa": {"h": "3", "f": "3", "r": "2", "s": ""},
  {"un": "1301", "nameTW": "醋酸乙烯酯 (VAM / 乙酸乙烯酯)", "nameEN": "Vinyl acetate", "cas": "108-05-4", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "2", "s": ""},
  {"un": "1866", "nameTW": "聚氨酯樹脂 (PU樹脂 / Polyurethane)", "nameEN": "Polyurethane resin", "cas": "N/A", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "0", "s": ""},
  {"un": "2078", "nameTW": "甲苯二異氰酸酯 (TDI / 發泡劑原料)", "nameEN": "Toluene diisocyanate", "cas": "584-84-9", "class": "6.1", "nfpa": {"h": "3", "f": "1", "r": "1", "s": "<s>W</s>"},
  {"un": "2206", "nameTW": "異氰酸酯類 (MDI / 聚氨酯硬化劑)", "nameEN": "Isocyanates, toxic", "cas": "101-68-8", "class": "6.1", "nfpa": {"h": "3", "f": "1", "r": "1", "s": "<s>W</s>"},
  {"un": "2281", "nameTW": "六亞甲基二異氰酸酯 (HDI / 硬化劑)", "nameEN": "Hexamethylene diisocyanate", "cas": "822-06-0", "class": "6.1", "nfpa": {"h": "3", "f": "1", "r": "1", "s": "<s>W</s>"},
  {"un": "3101", "nameTW": "過氧化甲乙酮 (MEKPO / FRP硬化劑)", "nameEN": "MEK peroxide", "cas": "1338-23-4", "class": "5.2", "nfpa": {"h": "3", "f": "2", "r": "4", "s": "OX"},
  {"un": "1491", "nameTW": "過氧化二苯甲醯 (BPO / 麵粉增白劑)", "nameEN": "Benzoyl peroxide", "cas": "94-36-0", "class": "5.2", "nfpa": {"h": "1", "f": "3", "r": "4", "s": "OX"},
  {"un": "3103", "nameTW": "有機過氧化物C型 (液體)", "nameEN": "Organic peroxide type C", "cas": "N/A", "class": "5.2", "nfpa": {"h": "2", "f": "3", "r": "3", "s": ""},
  {"un": "1866", "nameTW": "環氧樹脂 (EPOXY / 樹脂主劑)", "nameEN": "Resin solution", "cas": "N/A", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "0", "s": ""},
  {"un": "1133", "nameTW": "強力膠 (含甲苯/二甲苯接著劑)", "nameEN": "Adhesives", "cas": "N/A", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "0", "s": ""},
  {"un": "1325", "nameTW": "易燃固體 (未指明 / 固體酒精)", "nameEN": "Flammable solid", "cas": "N/A", "class": "4.1", "nfpa": {"h": "1", "f": "3", "r": "0", "s": ""},
  {"un": "1334", "nameTW": "萘 (Naphthalene / 樟腦丸原料)", "nameEN": "Naphthalene", "cas": "91-20-3", "class": "4.1", "nfpa": {"h": "2", "f": "2", "r": "0", "s": ""},
  {"un": "1350", "nameTW": "硫磺 (固體硫磺 / 硫粉)", "nameEN": "Sulfur", "cas": "7704-34-9", "class": "4.1", "nfpa": {"h": "2", "f": "1", "r": "0", "s": ""},
  {"un": "1338", "nameTW": "紅磷 (赤磷 / 磷粉)", "nameEN": "Phosphorus, amorphous", "cas": "7723-14-0", "class": "4.1", "nfpa": {"h": "1", "f": "1", "r": "1", "s": ""},
  {"un": "1328", "nameTW": "烏洛托品 (烏洛托品 / 固體燃料)", "nameEN": "Hexamethylenetetramine", "cas": "100-97-0", "class": "4.1", "nfpa": {"h": "2", "f": "2", "r": "1", "s": ""},
  {"un": "2781", "nameTW": "巴拉刈 (Paraquat / 固殺草 / 除草劑)", "nameEN": "Bipyridilium pesticide", "cas": "1910-42-5", "class": "6.1", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "2783", "nameTW": "陶斯松 (Chlorpyrifos / 有機磷農藥)", "nameEN": "Organophosphorus pesticide", "cas": "2921-88-2", "class": "6.1", "nfpa": {"h": "3", "f": "2", "r": "0", "s": ""},
  {"un": "2757", "nameTW": "滅靈 (Methomyl / 納乃得 / 氨基甲酸鹽)", "nameEN": "Carbamate pesticide", "cas": "16752-77-5", "class": "6.1", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "3018", "nameTW": "年年春 (Glyphosate / 嘉磷塞 / 除草劑)", "nameEN": "Organophosphorus pesticide", "cas": "1071-83-6", "class": "9", "nfpa": {"h": "2", "f": "0", "r": "0", "s": ""},
  {"un": "1649", "nameTW": "四乙基焦磷酸 (TEPP / 殺蟲劑)", "nameEN": "Tetraethyl pyrophosphate", "cas": "107-49-3", "class": "6.1", "nfpa": {"h": "4", "f": "1", "r": "1", "s": ""},
  {"un": "1942", "nameTW": "硝酸銨 (硝銨 / 肥料炸彈原料)", "nameEN": "Ammonium nitrate", "cas": "6484-52-2", "class": "5.1", "nfpa": {"h": "2", "f": "0", "r": "3", "s": "OX"},
  {"un": "1486", "nameTW": "硝酸鉀 (Potassium nitrate / 黑火藥原料)", "nameEN": "Potassium nitrate", "cas": "7757-79-1", "class": "5.1", "nfpa": {"h": "1", "f": "0", "r": "0", "s": "OX"},
  {"un": "1680", "nameTW": "氰化鉀 (KCN / 山埃 / 氰化物)", "nameEN": "Potassium cyanide", "cas": "151-50-8", "class": "6.1", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "1689", "nameTW": "氰化鈉 (NaCN / 青化鈉)", "nameEN": "Sodium cyanide", "cas": "143-33-9", "class": "6.1", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "1051", "nameTW": "氰化氫 (HCN / 氫氰酸)", "nameEN": "Hydrogen cyanide", "cas": "74-90-8", "class": "6.1", "nfpa": {"h": "4", "f": "4", "r": "2", "s": ""},
  {"un": "2024", "nameTW": "汞化合物 (汞 / 水銀類劇毒)", "nameEN": "Mercury compound", "cas": "N/A", "class": "6.1", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "1556", "nameTW": "砷化合物 (砒霜類)", "nameEN": "Arsenic compound", "cas": "N/A", "class": "6.1", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "1564", "nameTW": "鋇化合物 (鋇鹽)", "nameEN": "Barium compound", "cas": "N/A", "class": "6.1", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "1613", "nameTW": "氫氰酸水溶液 (HCN solution)", "nameEN": "Hydrocyanic acid", "cas": "74-90-8", "class": "6.1", "nfpa": {"h": "4", "f": "4", "r": "2", "s": ""},
  {"un": "1756", "nameTW": "氟化鉻 (Chromic fluoride)", "nameEN": "Chromic fluoride", "cas": "7788-97-8", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "2291", "nameTW": "含鉛化合物 (鉛鹽)", "nameEN": "Lead compound", "cas": "N/A", "class": "6.1", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "1624", "nameTW": "氯化汞 (昇汞)", "nameEN": "Mercuric chloride", "cas": "7487-94-7", "class": "6.1", "nfpa": {"h": "4", "f": "0", "r": "0", "s": ""},
  {"un": "2588", "nameTW": "農藥 (固體 / 未指明)", "nameEN": "Pesticide, solid, toxic", "cas": "N/A", "class": "6.1", "nfpa": {"h": "3", "f": "1", "r": "0", "s": ""},
  {"un": "2902", "nameTW": "農藥 (液體 / 未指明)", "nameEN": "Pesticide, liquid, toxic", "cas": "N/A", "class": "6.1", "nfpa": {"h": "3", "f": "2", "r": "0", "s": ""},
  {"un": "1962", "nameTW": "二氟化二氯矽烷 (Etching gas)", "nameEN": "Dichlorodifluorosilane", "cas": "18365-30-5", "class": "2.3", "nfpa": {"h": "3", "f": "0", "r": "1", "s": "<s>W</s>"},
  {"un": "2606", "nameTW": "甲基原矽酸甲酯", "nameEN": "Methyl orthosilicate", "cas": "681-84-5", "class": "6.1", "nfpa": {"h": "3", "f": "3", "r": "1", "s": ""},
  {"un": "1098", "nameTW": "烯丙醇 (Allyl alcohol)", "nameEN": "Allyl alcohol", "cas": "107-18-6", "class": "6.1", "nfpa": {"h": "4", "f": "3", "r": "0", "s": ""},
  {"un": "1182", "nameTW": "氯甲酸甲酯 (Methyl chloroformate)", "nameEN": "Ethyl chloroformate", "cas": "79-22-1", "class": "6.1", "nfpa": {"h": "4", "f": "3", "r": "1", "s": "<s>W</s>"},
  {"un": "1143", "nameTW": "巴豆醛 (Crotonaldehyde)", "nameEN": "Crotonaldehyde", "cas": "4170-30-3", "class": "6.1", "nfpa": {"h": "4", "f": "3", "r": "2", "s": ""},
  {"un": "2295", "nameTW": "氯乙酸甲酯", "nameEN": "Methyl chloroacetate", "cas": "96-34-4", "class": "6.1", "nfpa": {"h": "3", "f": "2", "r": "0", "s": ""},
  {"un": "1722", "nameTW": "氯化丙烯 (Allyl chloride)", "nameEN": "Allyl chloride", "cas": "107-05-1", "class": "3", "nfpa": {"h": "3", "f": "3", "r": "1", "s": ""},
  {"un": "1605", "nameTW": "二溴乙烷 (Ethylene dibromide)", "nameEN": "Ethylene dibromide", "cas": "106-93-4", "class": "6.1", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "1673", "nameTW": "對苯二胺", "nameEN": "Phenylenediamine", "cas": "106-50-3", "class": "6.1", "nfpa": {"h": "3", "f": "1", "r": "0", "s": ""},
  {"un": "2788", "nameTW": "有機錫化合物 (液態)", "nameEN": "Organotin compound", "cas": "N/A", "class": "6.1", "nfpa": {"h": "3", "f": "1", "r": "0", "s": ""},
  {"un": "1092", "nameTW": "丙烯醛 (Acrolein)", "nameEN": "Acrolein", "cas": "107-02-8", "class": "6.1", "nfpa": {"h": "4", "f": "3", "r": "2", "s": ""},
  {"un": "2794", "nameTW": "電池液 (酸性 / 硫酸)", "nameEN": "Battery fluid, acid", "cas": "7664-93-9", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "2", "s": "<span style='font-size:0.7em'><s>W</s><br>ACID</span>"},
  {"un": "2795", "nameTW": "電池液 (鹼性 / 氫氧化鉀)", "nameEN": "Battery fluid, alkali", "cas": "1310-58-3", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "1", "s": "COR"},
  {"un": "3480", "nameTW": "鋰離子電池 (Li-ion battery)", "nameEN": "Lithium ion batteries", "cas": "N/A", "class": "9", "nfpa": {"h": "2", "f": "3", "r": "3", "s": "<s>W</s>"},
  {"un": "3090", "nameTW": "鋰金屬電池 (Lithium metal battery)", "nameEN": "Lithium metal batteries", "cas": "N/A", "class": "9", "nfpa": {"h": "3", "f": "3", "r": "3", "s": "<s>W</s>"},
  {"un": "2735", "nameTW": "胺類 (液體腐蝕易燃 / Amines)", "nameEN": "Amines, liquid, corrosive", "cas": "N/A", "class": "8", "nfpa": {"h": "3", "f": "2", "r": "0", "s": ""},
  {"un": "1479", "nameTW": "氧化性固體 (未指明)", "nameEN": "Oxidizing solid, nos", "cas": "N/A", "class": "5.1", "nfpa": {"h": "2", "f": "0", "r": "1", "s": "OX"},
  {"un": "3139", "nameTW": "氧化性液體 (未指明)", "nameEN": "Oxidizing liquid, nos", "cas": "N/A", "class": "5.1", "nfpa": {"h": "3", "f": "0", "r": "1", "s": "OX"},
  {"un": "2814", "nameTW": "感染性物質 (對人有害 / 醫療廢棄物)", "nameEN": "Infectious substance", "cas": "N/A", "class": "6.2", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "3291", "nameTW": "醫療廢棄物 (未指明 / Biomedical waste)", "nameEN": "Clinical waste", "cas": "N/A", "class": "6.2", "nfpa": {"h": "2", "f": "1", "r": "0", "s": ""},
  {"un": "1760", "nameTW": "腐蝕性液體 (未指明 / 酸鹼廢液)", "nameEN": "Corrosive liquid, nos", "cas": "N/A", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "1759", "nameTW": "腐蝕性固體 (未指明)", "nameEN": "Corrosive solid, nos", "cas": "N/A", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "1", "s": ""},
  {"un": "3264", "nameTW": "腐蝕性液體 (酸性 無機)", "nameEN": "Corrosive liquid, acidic", "cas": "N/A", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "1", "s": "COR"},
  {"un": "3266", "nameTW": "腐蝕性液體 (鹼性 無機)", "nameEN": "Corrosive liquid, basic", "cas": "N/A", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "1", "s": "COR"},
  {"un": "2922", "nameTW": "腐蝕性液體 (具毒性)", "nameEN": "Corrosive liquid, toxic", "cas": "N/A", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "3316", "nameTW": "化學毒劑 (未指明 / 化學武器)", "nameEN": "Chemical kit", "cas": "N/A", "class": "9", "nfpa": {"h": "4", "f": "1", "r": "1", "s": ""},
  {"un": "2919", "nameTW": "放射性物質 (固態/包裝 / 核醫材)", "nameEN": "Radioactive material", "cas": "N/A", "class": "7", "nfpa": {"h": "4", "f": "0", "r": "0", "s": "RAD"},
  {"un": "2910", "nameTW": "放射性物質 (微量包裹)", "nameEN": "Radioactive material, excepted", "cas": "N/A", "class": "7", "nfpa": {"h": "1", "f": "0", "r": "0", "s": "RAD"},
  {"un": "2212", "nameTW": "藍石綿 (Asbestos / 石棉)", "nameEN": "Asbestos, blue", "cas": "12001-28-4", "class": "9", "nfpa": {"h": "2", "f": "0", "r": "0", "s": ""},
  {"un": "2315", "nameTW": "多氯聯苯 (PCB / 絕緣油)", "nameEN": "Polychlorinated biphenyls", "cas": "1336-36-3", "class": "9", "nfpa": {"h": "2", "f": "1", "r": "0", "s": ""},
  {"un": "3077", "nameTW": "危害環境物質 (固體 / 廢棄物)", "nameEN": "Env. hazardous solid", "cas": "N/A", "class": "9", "nfpa": {"h": "1", "f": "1", "r": "0", "s": ""},
  {"un": "1105", "nameTW": "戊醇 (Pentanol)", "nameEN": "Pentanols", "cas": "71-41-0", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "0", "s": ""},
  {"un": "1121", "nameTW": "環戊烷 (Cyclopentane)", "nameEN": "Cyclopentane", "cas": "287-92-3", "class": "3", "nfpa": {"h": "1", "f": "3", "r": "0", "s": ""},
  {"un": "1148", "nameTW": "雙丙酮醇 (Diacetone alcohol)", "nameEN": "Diacetone alcohol", "cas": "123-42-2", "class": "3", "nfpa": {"h": "1", "f": "2", "r": "0", "s": ""},
  {"un": "1153", "nameTW": "二甲醚 (液態 / 乙二醇二甲醚)", "nameEN": "Ethylene glycol dimethyl ether", "cas": "110-71-4", "class": "3", "nfpa": {"h": "2", "f": "2", "r": "0", "s": ""},
  {"un": "1166", "nameTW": "二氧戊環 (Dioxolane)", "nameEN": "Dioxolane", "cas": "646-06-0", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "0", "s": ""},
  {"un": "1188", "nameTW": "乙二醇單甲醚 (Methoxymercaptoethane)", "nameEN": "Ethylene glycol monomethyl ether", "cas": "109-86-4", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "0", "s": ""},
  {"un": "1190", "nameTW": "甲酸乙酯 (Ethyl formate)", "nameEN": "Ethyl formate", "cas": "109-94-4", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "0", "s": ""},
  {"un": "1218", "nameTW": "異戊二烯 (Isoprene)", "nameEN": "Isoprene", "cas": "78-79-5", "class": "3", "nfpa": {"h": "2", "f": "4", "r": "2", "s": ""},
  {"un": "1224", "nameTW": "環戊酮 (Cyclopentanone)", "nameEN": "Cyclopentanone", "cas": "120-92-3", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "0", "s": ""},
  {"un": "1246", "nameTW": "甲基環戊烷 (Methylcyclopentane)", "nameEN": "Methylcyclopentane", "cas": "96-37-7", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "0", "s": ""},
  {"un": "1261", "nameTW": "硝基甲烷 (Nitromethane)", "nameEN": "Nitromethane", "cas": "75-52-5", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "4", "s": ""},
  {"un": "1274", "nameTW": "正丙醇 (n-Propanol)", "nameEN": "n-Propanol", "cas": "71-23-8", "class": "3", "nfpa": {"h": "1", "f": "3", "r": "0", "s": ""},
  {"un": "1275", "nameTW": "丙醛 (Propionaldehyde)", "nameEN": "Propionaldehyde", "cas": "123-38-6", "class": "3", "nfpa": {"h": "3", "f": "3", "r": "2", "s": ""},
  {"un": "1282", "nameTW": "吡啶 (Pyridine / 臭味劑)", "nameEN": "Pyridine", "cas": "110-86-1", "class": "3", "nfpa": {"h": "3", "f": "3", "r": "0", "s": ""},
  {"un": "1308", "nameTW": "鋯化合物 (液體 / 易燃)", "nameEN": "Zirconium suspended in a liquid", "cas": "N/A", "class": "3", "nfpa": {"h": "1", "f": "3", "r": "0", "s": ""},
  {"un": "1863", "nameTW": "航空燃油 (Jet fuel / 噴射機油)", "nameEN": "Fuel, aviation, turbine engine", "cas": "N/A", "class": "3", "nfpa": {"h": "1", "f": "2", "r": "0", "s": ""},
  {"un": "1915", "nameTW": "環己酮 (Cyclohexanone)", "nameEN": "Cyclohexanone", "cas": "108-94-1", "class": "3", "nfpa": {"h": "1", "f": "2", "r": "0", "s": ""},
  {"un": "1920", "nameTW": "壬烷 (Nonanes)", "nameEN": "Nonanes", "cas": "111-84-2", "class": "3", "nfpa": {"h": "0", "f": "3", "r": "0", "s": ""},
  {"un": "1999", "nameTW": "焦油液 (Tars, liquid)", "nameEN": "Tars, liquid", "cas": "N/A", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "0", "s": ""},
  {"un": "2046", "nameTW": "甲基異丙基酮", "nameEN": "Methyl isopropyl ketone", "cas": "563-80-4", "class": "3", "nfpa": {"h": "1", "f": "3", "r": "0", "s": ""},
  {"un": "2048", "nameTW": "二環戊二烯 (Dicyclopentadiene)", "nameEN": "Dicyclopentadiene", "cas": "77-73-6", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "1", "s": ""},
  {"un": "2053", "nameTW": "甲基戊醇 (Methyl amyl alcohol)", "nameEN": "Methyl isobutyl carbinol", "cas": "108-11-2", "class": "3", "nfpa": {"h": "2", "f": "2", "r": "0", "s": ""},
  {"un": "2222", "nameTW": "苯甲醚 (Anisole)", "nameEN": "Anisole", "cas": "100-66-3", "class": "3", "nfpa": {"h": "2", "f": "2", "r": "0", "s": ""},
  {"un": "2282", "nameTW": "己醇 (Hexanols)", "nameEN": "Hexanols", "cas": "111-27-3", "class": "3", "nfpa": {"h": "1", "f": "2", "r": "0", "s": ""},
  {"un": "2286", "nameTW": "異十二烷 (Isododecane)", "nameEN": "Pentamethylheptane", "cas": "31807-55-3", "class": "3", "nfpa": {"h": "0", "f": "2", "r": "0", "s": ""},
  {"un": "2348", "nameTW": "丙烯酸丁酯 (Butyl acrylates)", "nameEN": "Butyl acrylates", "cas": "141-32-2", "class": "3", "nfpa": {"h": "2", "f": "2", "r": "2", "s": ""},
  {"un": "2363", "nameTW": "硫醇乙烷 (Ethyl mercaptan / 瓦斯臭味劑)", "nameEN": "Ethyl mercaptan", "cas": "75-08-1", "class": "3", "nfpa": {"h": "2", "f": "4", "r": "0", "s": ""},
  {"un": "2370", "nameTW": "己烯 (Hexene)", "nameEN": "1-Hexene", "cas": "592-41-6", "class": "3", "nfpa": {"h": "1", "f": "3", "r": "0", "s": ""},
  {"un": "2398", "nameTW": "甲基三級丁基醚 (MTBE / 汽油添加劑)", "nameEN": "Methyl tert-butyl ether", "cas": "1634-04-4", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "0", "s": ""},
  {"un": "2498", "nameTW": "四氫化苯 (1,2,3,6-Tetrahydrobenzaldehyde)", "nameEN": "1,2,3,6-Tetrahydrobenzaldehyde", "cas": "100-50-5", "class": "3", "nfpa": {"h": "2", "f": "2", "r": "0", "s": ""},
  {"un": "2618", "nameTW": "乙烯基甲苯 (Vinyltoluenes)", "nameEN": "Vinyltoluenes", "cas": "25013-15-4", "class": "3", "nfpa": {"h": "2", "f": "2", "r": "2", "s": ""},
  {"un": "3295", "nameTW": "碳氫化合物 (未指明 / 混合溶劑)", "nameEN": "Hydrocarbons, liquid, n.o.s.", "cas": "N/A", "class": "3", "nfpa": {"h": "1", "f": "3", "r": "0", "s": ""},
  {"un": "3336", "nameTW": "硫醇類 (未指明 / 惡臭溶劑)", "nameEN": "Mercaptans, liquid, flammable", "cas": "N/A", "class": "3", "nfpa": {"h": "2", "f": "3", "r": "0", "s": ""},
  {"un": "3475", "nameTW": "乙醇與汽油混合物 (酒精汽油 / E85)", "nameEN": "Ethanol and gasoline mixture", "cas": "N/A", "class": "3", "nfpa": {"h": "1", "f": "3", "r": "0", "s": ""},
  {"un": "3494", "nameTW": "石油原油 (高閃火點 / Sour crude)", "nameEN": "Petroleum sour crude oil", "cas": "N/A", "class": "3", "nfpa": {"h": "3", "f": "3", "r": "0", "s": ""},
  {"un": "1719", "nameTW": "苛性鹼液體 (Caustic alkali liquid)", "nameEN": "Caustic alkali liquid, n.o.s.", "cas": "N/A", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "1", "s": ""},
  {"un": "1727", "nameTW": "氟化氫銨 (Ammonium bifluoride)", "nameEN": "Ammonium hydrogendifluoride", "cas": "1341-49-7", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "1753", "nameTW": "氯化鈦 (Titanium tetrachloride / 四氯化鈦)", "nameEN": "Titanium tetrachloride", "cas": "7550-45-0", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "2", "s": "<s>W</s>"},
  {"un": "1773", "nameTW": "氯化鐵 (無水 / Ferric chloride)", "nameEN": "Ferric chloride, anhydrous", "cas": "7705-08-0", "class": "8", "nfpa": {"h": "2", "f": "0", "r": "1", "s": "<s>W</s>"},
  {"un": "1778", "nameTW": "氟矽酸 (Fluorosilicic acid)", "nameEN": "Fluorosilicic acid", "cas": "16961-83-4", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "1783", "nameTW": "六亞甲基二胺 (Hexamethylenediamine)", "nameEN": "Hexamethylenediamine", "cas": "124-09-4", "class": "8", "nfpa": {"h": "3", "f": "1", "r": "0", "s": ""},
  {"un": "1787", "nameTW": "氫碘酸 (Hydriodic acid)", "nameEN": "Hydriodic acid", "cas": "10034-85-2", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "1", "s": ""},
  {"un": "1788", "nameTW": "氫溴酸 (Hydrobromic acid)", "nameEN": "Hydrobromic acid", "cas": "10035-10-6", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "1", "s": ""},
  {"un": "1803", "nameTW": "苯酚磺酸 (Phenolsulfonic acid)", "nameEN": "Phenolsulfonic acid", "cas": "1333-39-7", "class": "8", "nfpa": {"h": "3", "f": "1", "r": "0", "s": ""},
  {"un": "1806", "nameTW": "五氯化磷 (Phosphorus pentachloride)", "nameEN": "Phosphorus pentachloride", "cas": "10026-13-8", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "2", "s": "<s>W</s>"},
  {"un": "1807", "nameTW": "五氧化二磷 (Phosphorus pentoxide)", "nameEN": "Phosphorus pentoxide", "cas": "1314-56-3", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "2", "s": "<s>W</s>"},
  {"un": "1814", "nameTW": "氫氧化鉀溶液 (KOH / 液鹼)", "nameEN": "Potassium hydroxide, solution", "cas": "1310-58-3", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "1", "s": "COR"},
  {"un": "1824", "nameTW": "氫氧化鈉溶液 (NaOH / 液鹼)", "nameEN": "Sodium hydroxide solution", "cas": "1310-73-2", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "1", "s": ""},
  {"un": "1831", "nameTW": "發煙硫酸 (Fuming sulfuric acid / 硫酸)", "nameEN": "Sulfuric acid, fuming", "cas": "8014-95-7", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "2", "s": "<span style='font-size:0.7em'><s>W</s><br>ACID</span>"},
  {"un": "1832", "nameTW": "廢硫酸 (Spent sulfuric acid)", "nameEN": "Sulfuric acid, spent", "cas": "N/A", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "2", "s": "<s>W</s>"},
  {"un": "1839", "nameTW": "三氯乙酸 (Trichloroacetic acid)", "nameEN": "Trichloroacetic acid", "cas": "76-03-9", "class": "8", "nfpa": {"h": "3", "f": "1", "r": "0", "s": ""},
  {"un": "1840", "nameTW": "氯化鋅溶液 (Zinc chloride solution)", "nameEN": "Zinc chloride, solution", "cas": "7646-85-7", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "1903", "nameTW": "消毒劑 (腐蝕性液體 / Disinfectant)", "nameEN": "Disinfectant, liquid, corrosive", "cas": "N/A", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "1905", "nameTW": "亞硒酸 (Selenic acid)", "nameEN": "Selenic acid", "cas": "7783-08-6", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "1906", "nameTW": "污泥酸 (Sludge acid)", "nameEN": "Sludge acid", "cas": "N/A", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "2", "s": "<s>W</s>"},
  {"un": "2018", "nameTW": "氯乙酸 (固體 / Chloroacetic acid)", "nameEN": "Chloroacetic acid, solid", "cas": "79-11-8", "class": "6.1", "nfpa": {"h": "3", "f": "1", "r": "0", "s": ""},
  {"un": "2032", "nameTW": "硝酸 (紅發煙硝酸)", "nameEN": "Nitric acid, red fuming", "cas": "7697-37-2", "class": "8", "nfpa": {"h": "4", "f": "0", "r": "1", "s": "OX"},
  {"un": "2214", "nameTW": "鄰苯二甲酸酐 (Phthalic anhydride)", "nameEN": "Phthalic anhydride", "cas": "85-44-9", "class": "8", "nfpa": {"h": "3", "f": "1", "r": "0", "s": ""},
  {"un": "2215", "nameTW": "順丁烯二酸酐 (Maleic anhydride / 馬來酸酐)", "nameEN": "Maleic anhydride", "cas": "108-31-6", "class": "8", "nfpa": {"h": "3", "f": "1", "r": "1", "s": ""},
  {"un": "2439", "nameTW": "氫氟酸鈉 (Sodium hydrogendifluoride)", "nameEN": "Sodium hydrogendifluoride", "cas": "1333-83-1", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "2505", "nameTW": "氟化銨 (Ammonium fluoride)", "nameEN": "Ammonium fluoride", "cas": "12125-01-8", "class": "6.1", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "2582", "nameTW": "三氯化鐵溶液 (Ferric chloride solution)", "nameEN": "Ferric chloride solution", "cas": "7705-08-0", "class": "8", "nfpa": {"h": "2", "f": "0", "r": "0", "s": ""},
  {"un": "2586", "nameTW": "烷基磺酸 (Alkyl sulfonic acids)", "nameEN": "Alkyl sulfonic acids, liquid", "cas": "N/A", "class": "8", "nfpa": {"h": "3", "f": "1", "r": "0", "s": ""},
  {"un": "2679", "nameTW": "氫氧化鋰溶液 (Lithium hydroxide sol.)", "nameEN": "Lithium hydroxide solution", "cas": "1310-66-3", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "1", "s": ""},
  {"un": "2693", "nameTW": "亞硫酸氫鹽水溶液 (Bisulfites, solution)", "nameEN": "Bisulfites, aqueous solution", "cas": "N/A", "class": "8", "nfpa": {"h": "2", "f": "0", "r": "0", "s": ""},
  {"un": "2734", "nameTW": "胺類 (腐蝕液體具毒性 / Amines)", "nameEN": "Amines, liquid, corrosive, toxic", "cas": "N/A", "class": "8", "nfpa": {"h": "3", "f": "1", "r": "0", "s": ""},
  {"un": "2790", "nameTW": "醋酸溶液 (Acetic acid solution / 乙酸)", "nameEN": "Acetic acid solution", "cas": "64-19-7", "class": "8", "nfpa": {"h": "2", "f": "2", "r": "0", "s": ""},
  {"un": "2796", "nameTW": "硫酸液 (含酸量不大於51%)", "nameEN": "Sulfuric acid (not > 51%)", "cas": "7664-93-9", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "1", "s": ""},
  {"un": "2817", "nameTW": "二氟化氫銨溶液 (Ammonium bifluoride sol.)", "nameEN": "Ammonium hydrogendifluoride sol.", "cas": "1341-49-7", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "3265", "nameTW": "腐蝕性液體 (酸性 有機)", "nameEN": "Corrosive liquid, acidic, organic", "cas": "N/A", "class": "8", "nfpa": {"h": "3", "f": "1", "r": "0", "s": "COR"},
  {"un": "3267", "nameTW": "腐蝕性液體 (鹼性 有機)", "nameEN": "Corrosive liquid, basic, organic", "cas": "N/A", "class": "8", "nfpa": {"h": "3", "f": "1", "r": "0", "s": "COR"},
  {"un": "3301", "nameTW": "腐蝕性液體 (自身發熱)", "nameEN": "Corrosive liquid, self-heating", "cas": "N/A", "class": "8", "nfpa": {"h": "3", "f": "1", "r": "1", "s": ""},
  {"un": "3412", "nameTW": "甲酸 (蟻酸 / Formic acid)", "nameEN": "Formic acid", "cas": "64-18-6", "class": "8", "nfpa": {"h": "3", "f": "2", "r": "0", "s": "COR"},
  {"un": "3496", "nameTW": "鎳氫電池 (NiMH battery)", "nameEN": "Batteries, nickel-metal hydride", "cas": "N/A", "class": "9", "nfpa": {"h": "1", "f": "0", "r": "0", "s": ""},
  {"un": "3498", "nameTW": "碘化氫溶液 (氫碘酸)", "nameEN": "Iodine pentafluoride", "cas": "7783-66-6", "class": "8", "nfpa": {"h": "3", "f": "0", "r": "1", "s": "OX"},
  {"un": "1541", "nameTW": "丙酮氰醇 (Acetone cyanohydrin)", "nameEN": "Acetone cyanohydrin", "cas": "75-86-5", "class": "6.1", "nfpa": {"h": "4", "f": "2", "r": "2", "s": ""},
  {"un": "1544", "nameTW": "生物鹼類 (Alkaloids / 毒性固體)", "nameEN": "Alkaloids, solid, n.o.s.", "cas": "N/A", "class": "6.1", "nfpa": {"h": "3", "f": "1", "r": "0", "s": ""},
  {"un": "1557", "nameTW": "砷化合物 (液體 / 砒霜類液體)", "nameEN": "Arsenic compound, liquid", "cas": "N/A", "class": "6.1", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "1560", "nameTW": "三氯化砷 (Arsenic trichloride)", "nameEN": "Arsenic trichloride", "cas": "7784-34-1", "class": "6.1", "nfpa": {"h": "3", "f": "0", "r": "1", "s": ""},
  {"un": "1566", "nameTW": "鈹化合物 (鈹鹽 / 固體)", "nameEN": "Beryllium compound", "cas": "N/A", "class": "6.1", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "1570", "nameTW": "番木鱉鹼 (Brucine)", "nameEN": "Brucine", "cas": "357-57-3", "class": "6.1", "nfpa": {"h": "4", "f": "1", "r": "0", "s": ""},
  {"un": "1580", "nameTW": "苦味酸 (Picric acid / 氯化苦)", "nameEN": "Chloropicrin", "cas": "76-06-2", "class": "6.1", "nfpa": {"h": "4", "f": "0", "r": "3", "s": ""},
  {"un": "1583", "nameTW": "三氯硝基甲烷混合物 (催淚瓦斯)", "nameEN": "Chloropicrin mixture", "cas": "N/A", "class": "6.1", "nfpa": {"h": "4", "f": "0", "r": "1", "s": ""},
  {"un": "1591", "nameTW": "鄰二氯苯 (o-Dichlorobenzene)", "nameEN": "o-Dichlorobenzene", "cas": "95-50-1", "class": "6.1", "nfpa": {"h": "2", "f": "2", "r": "0", "s": ""},
  {"un": "1602", "nameTW": "染料 (液體 / 毒性)", "nameEN": "Dye, liquid, toxic", "cas": "N/A", "class": "6.1", "nfpa": {"h": "3", "f": "1", "r": "0", "s": ""},
  {"un": "1611", "nameTW": "六乙基四磷酸酯 (農藥)", "nameEN": "Hexaethyl tetraphosphate", "cas": "757-58-4", "class": "6.1", "nfpa": {"h": "4", "f": "1", "r": "1", "s": ""},
  {"un": "1614", "nameTW": "氰化氫吸附於惰性物", "nameEN": "Hydrogen cyanide, absorbed", "cas": "74-90-8", "class": "6.1", "nfpa": {"h": "4", "f": "4", "r": "2", "s": ""},
  {"un": "1634", "nameTW": "溴化汞 (Mercuric bromide)", "nameEN": "Mercuric bromides", "cas": "7789-47-1", "class": "6.1", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "1638", "nameTW": "碘化汞 (Mercuric iodide)", "nameEN": "Mercury iodide", "cas": "7774-29-0", "class": "6.1", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "1647", "nameTW": "溴甲烷與乙烯二溴化物混合物", "nameEN": "Methyl bromide and ethylene dibromide", "cas": "N/A", "class": "6.1", "nfpa": {"h": "3", "f": "0", "r": "0", "s": ""},
  {"un": "1653", "nameTW": "對甲苯腈 (p-Tolunitrile)", "nameEN": "Tolunitriles, liquid", "cas": "104-85-8", "class": "6.1", "nfpa": {"h": "2", "f": "2", "r": "0", "s": ""},
  {"un": "1655", "nameTW": "尼古丁化合物 (Nicotine compound)", "nameEN": "Nicotine compound", "cas": "N/A", "class": "6.1", "nfpa": {"h": "4", "f": "1", "r": "0", "s": ""},
  {"un": "1656", "nameTW": "鹽酸尼古丁溶液 (Nicotine hydrochloride)", "nameEN": "Nicotine hydrochloride, sol.", "cas": "N/A", "class": "6.1", "nfpa": {"h": "4", "f": "0", "r": "0", "s": ""},
  {"un": "1674", "nameTW": "苯汞胺 (Phenylmercuric acetate)", "nameEN": "Phenylmercuric acetate", "cas": "62-38-4", "class": "6.1", "nfpa": {"h": "3", "f": "1", "r": "0", "s": ""},
  {"un": "1688", "nameTW": "疊氮化鈉 (Sodium azide / 汽車安全氣囊原料)", "nameEN": "Sodium azide", "cas": "26628-22-8", "class": "6.1", "nfpa": {"h": "4", "f": "1", "r": "2", "s": ""},
  {"un": "1692", "nameTW": "士的寧 (Strychnine / 番木鱉鹼)", "nameEN": "Strychnine", "cas": "57-24-9", "class": "6.1", "nfpa": {"h": "4", "f": "0", "r": "0", "s": ""},
  {"un": "1695", "nameTW": "氯化亞氯乙酸", "nameEN": "Chloroacetone", "cas": "78-95-5", "class": "6.1", "nfpa": {"h": "4", "f": "2", "r": "0", "s": ""},
  {"un": "1700", "nameTW": "催淚瓦斯彈 (Tear gas candles)", "nameEN": "Tear gas candles", "cas": "N/A", "class": "6.1", "nfpa": {"h": "2", "f": "1", "r": "1", "s": ""},
  {"un": "2020", "nameTW": "氯酚 (Chlorophenols / 固體)", "nameEN": "Chlorophenols, solid", "cas": "25167-80-0", "class": "6.1", "nfpa": {"h": "3", "f": "1", "r": "0", "s": ""},
  {"un": "2021", "nameTW": "氯酚 (Chlorophenols / 液體)", "nameEN": "Chlorophenols, liquid", "cas": "25167-80-0", "class": "6.1", "nfpa": {"h": "3", "f": "1", "r": "0", "s": ""},
  {"un": "2583", "nameTW": "烷基磺酸 (固體)", "nameEN": "Alkyl sulfonic acids, solid", "cas": "N/A", "class": "8", "nfpa": {"h": "3", "f": "1", "r": "0", "s": ""},
  {"un": "2758", "nameTW": "氨基甲酸鹽農藥 (固體)", "nameEN": "Carbamate pesticide, solid", "cas": "N/A", "class": "6.1", "nfpa": {"h": "3", "f": "1", "r": "0", "s": ""},
  {"un": "2771", "nameTW": "二硫代氨基甲酸鹽 (農藥)", "nameEN": "Thiocarbamate pesticide", "cas": "N/A", "class": "6.1", "nfpa": {"h": "3", "f": "1", "r": "0", "s": ""},
  {"un": "2784", "nameTW": "有機磷農藥 (液體易燃 / 巴拉松類)", "nameEN": "Organophosphorus pesticide, fl.", "cas": "N/A", "class": "3", "nfpa": {"h": "3", "f": "3", "r": "0", "s": ""},
  {"un": "2813", "nameTW": "防水劑 (固體腐蝕性)", "nameEN": "Water reactive solid, corrosive", "cas": "N/A", "class": "8", "nfpa": {"h": "3", "f": "1", "r": "2", "s": "<s>W</s>"},
  {"un": "1002", "nameTW": "空氣 (壓縮空氣)", "nameEN": "Air, compressed", "cas": "132259-10-0", "class": "2.2", "nfpa": {"h": "0", "f": "0", "r": "0", "s": ""},
  {"un": "1006", "nameTW": "氬氣 (壓縮氬氣 / Argon)", "nameEN": "Argon, compressed", "cas": "7440-37-1", "class": "2.2", "nfpa": {"h": "0", "f": "0", "r": "0", "s": "SA"},
  {"un": "1009", "nameTW": "溴三氟甲烷 (R-13B1 / 海龍 1301)", "nameEN": "Bromotrifluoromethane", "cas": "75-63-8", "class": "2.2", "nfpa": {"h": "1", "f": "0", "r": "0", "s": ""},
  {"un": "1018", "nameTW": "氯二氟甲烷 (R-22 / 舊式冷媒)", "nameEN": "Chlorodifluoromethane", "cas": "75-45-6", "class": "2.2", "nfpa": {"h": "1", "f": "0", "r": "0", "s": ""},
  {"un": "1020", "nameTW": "氯五氟乙烷 (R-115)", "nameEN": "Chloropentafluoroethane", "cas": "76-15-3", "class": "2.2", "nfpa": {"h": "1", "f": "0", "r": "0", "s": ""},
  {"un": "1021", "nameTW": "氯四氟乙烷 (R-124)", "nameEN": "1-Chloro-1,2,2,2-tetrafluoroethane", "cas": "2837-89-0", "class": "2.2", "nfpa": {"h": "1", "f": "0", "r": "0", "s": ""},
  {"un": "1022", "nameTW": "三氟氯甲烷 (R-13)", "nameEN": "Chlorotrifluoromethane", "cas": "75-72-9", "class": "2.2", "nfpa": {"h": "1", "f": "0", "r": "0", "s": ""},
  {"un": "1027", "nameTW": "環丙烷 (Cyclopropane)", "nameEN": "Cyclopropane", "cas": "75-19-4", "class": "2.1", "nfpa": {"h": "1", "f": "4", "r": "0", "s": ""},
  {"un": "1028", "nameTW": "二氯二氟甲烷 (R-12)", "nameEN": "Dichlorodifluoromethane", "cas": "75-71-8", "class": "2.2", "nfpa": {"h": "1", "f": "0", "r": "0", "s": ""},
  {"un": "1029", "nameTW": "二氯氟甲烷 (R-21)", "nameEN": "Dichlorofluoromethane", "cas": "75-43-4", "class": "2.2", "nfpa": {"h": "1", "f": "0", "r": "0", "s": ""},
  {"un": "1032", "nameTW": "二甲胺 (無水 / Dimethylamine)", "nameEN": "Dimethylamine, anhydrous", "cas": "124-40-3", "class": "2.1", "nfpa": {"h": "3", "f": "4", "r": "0", "s": ""},
  {"un": "1036", "nameTW": "乙胺 (Ethylamine)", "nameEN": "Ethylamine", "cas": "75-04-7", "class": "2.1", "nfpa": {"h": "3", "f": "4", "r": "0", "s": ""},
  {"un": "1041", "nameTW": "環氧乙烷與二氧化碳混合氣", "nameEN": "Ethylene oxide and CO2 mixture", "cas": "N/A", "class": "2.1", "nfpa": {"h": "2", "f": "4", "r": "3", "s": ""},
  {"un": "1046", "nameTW": "氦氣 (壓縮氦氣 / Helium)", "nameEN": "Helium, compressed", "cas": "7440-59-7", "class": "2.2", "nfpa": {"h": "0", "f": "0", "r": "0", "s": "SA"},
  {"un": "1052", "nameTW": "氟化氫 (無水 / HF)", "nameEN": "Hydrogen fluoride, anhydrous", "cas": "7664-39-3", "class": "2.3", "nfpa": {"h": "4", "f": "0", "r": "1", "s": ""},
  {"un": "1055", "nameTW": "異丁烯 (Isobutylene)", "nameEN": "Isobutylene", "cas": "115-11-7", "class": "2.1", "nfpa": {"h": "1", "f": "4", "r": "0", "s": ""},
  {"un": "1056", "nameTW": "氪氣 (Krypton)", "nameEN": "Krypton, compressed", "cas": "7439-90-9", "class": "2.2", "nfpa": {"h": "0", "f": "0", "r": "0", "s": "SA"},
  {"un": "1058", "nameTW": "液化氣體 (不燃 / 未指明)", "nameEN": "Liquefied gases, non-flammable", "cas": "N/A", "class": "2.2", "nfpa": {"h": "1", "f": "0", "r": "0", "s": ""},
  {"un": "1060", "nameTW": "丙炔與丙二烯混合物 (焊接氣)", "nameEN": "Methylacetylene and propadiene mixture", "cas": "N/A", "class": "2.1", "nfpa": {"h": "2", "f": "4", "r": "3", "s": ""},
  {"un": "1061", "nameTW": "甲胺 (無水 / Methylamine)", "nameEN": "Methylamine, anhydrous", "cas": "74-89-5", "class": "2.1", "nfpa": {"h": "3", "f": "4", "r": "0", "s": ""},
  {"un": "1063", "nameTW": "氯甲烷 (Methyl chloride)", "nameEN": "Methyl chloride", "cas": "74-87-3", "class": "2.1", "nfpa": {"h": "2", "f": "4", "r": "0", "s": ""},
  {"un": "1065", "nameTW": "氖氣 (Neon)", "nameEN": "Neon, compressed", "cas": "7440-01-9", "class": "2.2", "nfpa": {"h": "0", "f": "0", "r": "0", "s": "SA"},
  {"un": "1071", "nameTW": "油氣 (Oil gas / 壓縮燃氣)", "nameEN": "Oil gas, compressed", "cas": "N/A", "class": "2.1", "nfpa": {"h": "1", "f": "4", "r": "0", "s": ""},
  {"un": "1077", "nameTW": "丙烯 (Propylene)", "nameEN": "Propylene", "cas": "115-07-1", "class": "2.1", "nfpa": {"h": "1", "f": "4", "r": "1", "s": ""},
  {"un": "1078", "nameTW": "冷媒氣體 (未指明)", "nameEN": "Refrigerant gas, n.o.s.", "cas": "N/A", "class": "2.2", "nfpa": {"h": "1", "f": "0", "r": "0", "s": ""},
  {"un": "1082", "nameTW": "三氟氯乙烯 (R-1113)", "nameEN": "Trifluorochloroethylene", "cas": "79-38-9", "class": "2.3", "nfpa": {"h": "3", "f": "4", "r": "2", "s": ""},
  {"un": "1083", "nameTW": "三甲胺 (無水 / Trimethylamine)", "nameEN": "Trimethylamine, anhydrous", "cas": "75-50-3", "class": "2.1", "nfpa": {"h": "3", "f": "4", "r": "0", "s": ""},
  {"un": "1085", "nameTW": "溴乙烯 (Vinyl bromide)", "nameEN": "Vinyl bromide", "cas": "593-60-2", "class": "2.1", "nfpa": {"h": "2", "f": "4", "r": "2", "s": ""},
  {"un": "1087", "nameTW": "甲基乙烯基醚", "nameEN": "Vinyl methyl ether", "cas": "107-25-5", "class": "2.1", "nfpa": {"h": "2", "f": "4", "r": "2", "s": ""},
  {"un": "1951", "nameTW": "氬與二氧化碳混合氣 (焊接氣)", "nameEN": "Argon and CO2 mixture", "cas": "N/A", "class": "2.2", "nfpa": {"h": "1", "f": "0", "r": "0", "s": "SA"},
  {"un": "1057", "nameTW": "打火機 (含易燃氣體)", "nameEN": "Lighters", "cas": "N/A", "class": "2.1", "nfpa": {"h": "1", "f": "4", "r": "0", "s": ""},
  {"un": "1856", "nameTW": "廢布 (塗料與易燃液體浸透 / 沾油抹布)", "nameEN": "Rags, oily", "cas": "N/A", "class": "4.2", "nfpa": {"h": "1", "f": "3", "r": "0", "s": ""},
  {"un": "1344", "nameTW": "三硝基酚 (苦味酸 / 含水大於30%)", "nameEN": "Trinitrophenol, wetted", "cas": "88-89-1", "class": "4.1", "nfpa": {"h": "3", "f": "4", "r": "4", "s": ""},
  {"un": "1352", "nameTW": "鈦粉 (Titanium powder, wetted)", "nameEN": "Titanium powder, wetted", "cas": "7440-32-6", "class": "4.1", "nfpa": {"h": "1", "f": "3", "r": "1", "s": "<s>W</s>"},
  {"un": "1361", "nameTW": "碳 (活性碳 / 炭粉)", "nameEN": "Carbon", "cas": "7440-44-0", "class": "4.2", "nfpa": {"h": "0", "f": "1", "r": "0", "s": ""},
  {"un": "1362", "nameTW": "活性碳 (自身發熱)", "nameEN": "Carbon, activated", "cas": "7440-44-0", "class": "4.2", "nfpa": {"h": "0", "f": "1", "r": "0", "s": ""},
  {"un": "1364", "nameTW": "棉花廢料 (含油)", "nameEN": "Cotton waste, oily", "cas": "N/A", "class": "4.2", "nfpa": {"h": "1", "f": "2", "r": "0", "s": ""},
  {"un": "1376", "nameTW": "氧化鐵廢料", "nameEN": "Iron oxide, spent", "cas": "1309-37-1", "class": "4.2", "nfpa": {"h": "1", "f": "1", "r": "0", "s": ""},
  {"un": "1378", "nameTW": "金屬催化劑 (自身發熱)", "nameEN": "Metal catalyst, wetted", "cas": "N/A", "class": "4.2", "nfpa": {"h": "2", "f": "3", "r": "1", "s": ""},
  {"un": "1380", "nameTW": "五硫化二磷 (Phosphorus pentasulfide)", "nameEN": "Phosphorus pentasulfide", "cas": "1314-80-3", "class": "4.3", "nfpa": {"h": "3", "f": "1", "r": "2", "s": "<s>W</s>"},
  {"un": "1382", "nameTW": "硫化鉀 (無水)", "nameEN": "Potassium sulfide, anhydrous", "cas": "1312-73-8", "class": "4.2", "nfpa": {"h": "3", "f": "1", "r": "0", "s": ""},
  {"un": "1384", "nameTW": "二硫亞磺酸鈉 (Sodium dithionite)", "nameEN": "Sodium dithionite", "cas": "7775-14-6", "class": "4.2", "nfpa": {"h": "2", "f": "1", "r": "2", "s": "<s>W</s>"},
  {"un": "1389", "nameTW": "鈉汞齊 (Alkali metal amalgam)", "nameEN": "Alkali metal amalgam", "cas": "N/A", "class": "4.3", "nfpa": {"h": "3", "f": "3", "r": "2", "s": "<s>W</s>"},
  {"un": "1391", "nameTW": "鹼金屬分散液 (Alkali metal dispersion)", "nameEN": "Alkali metal dispersion", "cas": "N/A", "class": "4.3", "nfpa": {"h": "3", "f": "3", "r": "2", "s": "<s>W</s>"},
  {"un": "1400", "nameTW": "鋇 (金屬鋇 / Barium)", "nameEN": "Barium", "cas": "7440-39-3", "class": "4.3", "nfpa": {"h": "3", "f": "1", "r": "2", "s": "<s>W</s>"},
  {"un": "1401", "nameTW": "鈣 (金屬鈣 / Calcium)", "nameEN": "Calcium", "cas": "7440-70-2", "class": "4.3", "nfpa": {"h": "3", "f": "1", "r": "2", "s": "<s>W</s>"},
  {"un": "1408", "nameTW": "矽鐵 (Ferrosilicon)", "nameEN": "Ferrosilicon", "cas": "8049-17-0", "class": "4.3", "nfpa": {"h": "1", "f": "0", "r": "2", "s": "<s>W</s>"},
  {"un": "1409", "nameTW": "金屬氫化物 (未指明)", "nameEN": "Metal hydrides, water-reactive", "cas": "N/A", "class": "4.3", "nfpa": {"h": "3", "f": "2", "r": "2", "s": "<s>W</s>"},
  {"un": "1413", "nameTW": "硼氫化鋰 (Lithium borohydride)", "nameEN": "Lithium borohydride", "cas": "10689-53-7", "class": "4.3", "nfpa": {"h": "3", "f": "2", "r": "2", "s": "<s>W</s>"},
  {"un": "1432", "nameTW": "磷化鈉 (Sodium phosphide)", "nameEN": "Sodium phosphide", "cas": "12058-85-4", "class": "4.3", "nfpa": {"h": "4", "f": "4", "r": "2", "s": "<s>W</s>"}
];